### ISSUE TITLE
panic: cannot add empty folder id

### ISSUE THREAD

**Issue by kreddy0404** [syncthing/syncthing-android#1007]
Continuous panic on syncthing master "panic: cannot add empty folder id"
[7X3Q4] INFO: syncthing v0.14.26 "Dysprosium Dragonfly" (go1.8 linux-amd64) jenkins@build.syncthing.net 2017-03-23 11:04:35 UTC
[7X3Q4] INFO: My ID: 7X3Q4YA-NCN6C6T-LCWTTUD-QQIIIEY-A4AYRHZ-H45ZBRN-MTMTAYU-DADLBA4
[7X3Q4] INFO: Single thread SHA256 performance is 236 MB/s using minio/sha256-simd (159 MB/s using crypto/sha256).
[7X3Q4] INFO: Hashing performance with weak hash is 197.50 MB/s
[7X3Q4] INFO: Hashing performance without weak hash is 223.40 MB/s
[7X3Q4] INFO: Weak hash enabled, as it has an acceptable performance impact.
[7X3Q4] INFO: Ready to synchronize "0160-master" (0160-master) (readwrite)
[7X3Q4] INFO: Ready to synchronize "0033" (0033) (readonly)
[7X3Q4] INFO: Ready to synchronize "0141-master" (0141-master) (readwrite)
[7X3Q4] INFO: Ready to synchronize "0292-master" (0292-master) (readwrite)
...
[7X3Q4] INFO: Ready to synchronize "0178" (0178) (readonly)
[7X3Q4] INFO: Ready to synchronize "0156-master" (0156-master) (readwrite)
[7X3Q4] INFO: Ready to synchronize "0083" (0083) (readonly)
[7X3Q4] INFO: Ready to synchronize "0510" (0510) (readonly)
[7X3Q4] INFO: Ready to synchronize "0324-master" (0324-master) (readwrite)
[7X3Q4] INFO: Ready to synchronize "0963" (0963) (readonly)
[7X3Q4] INFO: Ready to synchronize "0247-master" (0247-master) (readwrite)
[7X3Q4] INFO: Ready to synchronize "0245-master" (0245-master) (readwrite)
[7X3Q4] INFO: Ready to synchronize "0539" (0539) (readonly)
[7X3Q4] INFO: Ready to synchronize "9932-master" (9932-master) (readwrite)
[7X3Q4] INFO: Ready to synchronize "0269" (0269) (readonly)
[7X3Q4] INFO: Ready to synchronize "0289" (0289) (readonly)
[7X3Q4] INFO: Ready to synchronize "0132" (0132) (readonly)
[7X3Q4] INFO: Ready to synchronize "0077" (0077) (readonly)
[7X3Q4] INFO: Ready to synchronize "0376" (0376) (readonly)
[7X3Q4] INFO: Ready to synchronize "0363-master" (0363-master) (readwrite)
[7X3Q4] INFO: Ready to synchronize "0383" (0383) (readonly)
[7X3Q4] INFO: Ready to synchronize "0284" (0284) (readonly)
[7X3Q4] INFO: Ready to synchronize "0586-master" (0586-master) (readwrite)
[7X3Q4] INFO: Ready to synchronize "0530" (0530) (readonly)
[7X3Q4] INFO: Ready to synchronize "0380" (0380) (readonly)
[7X3Q4] INFO: Ready to synchronize "0239" (0239) (readonly)
[7X3Q4] INFO: Ready to synchronize "0325-master" (0325-master) (readwrite)
[7X3Q4] INFO: Ready to synchronize "9938-master" (9938-master) (readwrite)
[7X3Q4] INFO: Ready to synchronize "0312" (0312) (readonly)
[7X3Q4] INFO: Ready to synchronize "0472" (0472) (readonly)
[7X3Q4] INFO: Ready to synchronize "0333-master" (0333-master) (readwrite)
[7X3Q4] INFO: Ready to synchronize "0478" (0478) (readonly)
[7X3Q4] INFO: Ready to synchronize "0170" (0170) (readonly)
[7X3Q4] INFO: Ready to synchronize "0233" (0233) (readonly)
[7X3Q4] INFO: Ready to synchronize "0369-master" (0369-master) (readwrite)
[7X3Q4] INFO: Ready to synchronize "0549" (0549) (readonly)
[7X3Q4] INFO: Ready to synchronize "0067" (0067) (readonly)
[7X3Q4] INFO: Ready to synchronize "repos-master" (repos-master) (readwrite)
[7X3Q4] INFO: Ready to synchronize "0702" (0702) (readonly)
[7X3Q4] INFO: Ready to synchronize "0951-master" (0951-master) (readwrite)
[7X3Q4] INFO: Ready to synchronize "0570" (0570) (readonly)
[7X3Q4] INFO: Ready to synchronize "0129-master" (0129-master) (readwrite)
[7X3Q4] INFO: Ready to synchronize "0506-master" (0506-master) (readwrite)
[7X3Q4] INFO: Ready to synchronize "0288-master" (0288-master) (readwrite)
[7X3Q4] INFO: Ready to synchronize "0084-master" (0084-master) (readwrite)
[7X3Q4] INFO: Ready to synchronize "0233-master" (0233-master) (readwrite)
[7X3Q4] INFO: Ready to synchronize "0387-master" (0387-master) (readwrite)
[7X3Q4] INFO: Ready to synchronize "0358" (0358) (readonly)
Panic at 2018-01-23T15:23:14-06:00
panic: cannot add empty folder id

goroutine 1 [running]:
github.com/syncthing/syncthing/lib/model.(*Model).AddFolder(0xc42008aa00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42030d1c0, 0x1, ...)
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/model/model.go:303 +0x114
main.syncthingMain(0x0, 0x0, 0x0, 0x0, 0x0, 0x1, 0xb6e1b4, 0x1, 0x0, 0x0, ...)
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:820 +0x2cf1
main.main()
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:459 +0x5ac

goroutine 49 [select]:
github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc420392000)
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:90 +0x5d9
created by github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.openDB
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db.go:139 +0x583

goroutine 7 [chan receive]:
github.com/syncthing/syncthing/vendor/github.com/xtaci/kcp-go.(*Emitter).emitTask(0x109dbc8)
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/xtaci/kcp-go/emitter.go:37 +0x99
created by github.com/syncthing/syncthing/vendor/github.com/xtaci/kcp-go.(*Emitter).init
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/xtaci/kcp-go/emitter.go:32 +0x6c

goroutine 8 [select]:
github.com/syncthing/syncthing/vendor/github.com/xtaci/kcp-go.(*updateHeap).updateTask(0x10a01e0)
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/xtaci/kcp-go/updater.go:83 +0x4d7
created by github.com/syncthing/syncthing/vendor/github.com/xtaci/kcp-go.init.4
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/xtaci/kcp-go/updater.go:13 +0xb5

goroutine 9 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:116 +0x104
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 33 [select]:
github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc42009a000)
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:206 +0x23f
created by github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:237 +0x19c

goroutine 11 [chan receive]:
main.trackCPUUsage()
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:24 +0x103
created by main.init.3
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:17 +0x35

goroutine 12 [select, locked to thread]:
runtime.gopark(0xd13428, 0x0, 0xb71224, 0x6, 0x18, 0x2)
        /usr/local/go/src/runtime/proc.go:271 +0x13a
runtime.selectgoImpl(0xc4201c0f50, 0x0, 0x18)
        /usr/local/go/src/runtime/select.go:423 +0x1364
runtime.selectgo(0xc4201c0f50)
        /usr/local/go/src/runtime/select.go:238 +0x1c
runtime.ensureSigM.func1()
        /usr/local/go/src/runtime/signal_unix.go:434 +0x2dd
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1

goroutine 13 [chan receive]:
main.setupSignalHandling.func1(0xc4200671a0)
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:974 +0x40
created by main.setupSignalHandling
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:976 +0xbc

goroutine 14 [chan receive]:
main.setupSignalHandling.func2(0xc420067320)
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:984 +0x40
created by main.setupSignalHandling
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:986 +0x181

goroutine 15 [select]:
github.com/syncthing/syncthing/vendor/github.com/thejerf/suture.(*Supervisor).Serve(0xc42009a460)
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/thejerf/suture/supervisor.go:338 +0xf65
created by github.com/syncthing/syncthing/vendor/github.com/thejerf/suture.(*Supervisor).ServeBackground
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/thejerf/suture/supervisor.go:297 +0x43

goroutine 16 [chan receive]:
github.com/syncthing/syncthing/lib/events.(*bufferedSubscription).pollingLoop(0xc420048e60)
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/events/events.go:318 +0x83
created by github.com/syncthing/syncthing/lib/events.NewBufferedSubscription
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/events/events.go:313 +0x1ba

goroutine 17 [chan receive]:
github.com/syncthing/syncthing/lib/events.(*bufferedSubscription).pollingLoop(0xc420048eb0)
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/events/events.go:318 +0x83
created by github.com/syncthing/syncthing/lib/events.NewBufferedSubscription
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/events/events.go:313 +0x1ba

goroutine 50 [select]:
github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc420392000)
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db_state.go:101 +0x249
created by github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.openDB
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db.go:140 +0x5a5

goroutine 51 [select]:
github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc420392000)
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:804 +0x638
created by github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.openDB
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db.go:146 +0x722

goroutine 52 [select]:
github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc420392000)
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:751 +0x242
created by github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.openDB
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db.go:147 +0x744

goroutine 65 [select]:
github.com/syncthing/syncthing/lib/model.(*ProgressEmitter).Serve(0xc421c26500)
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/model/progressemitter.go:56 +0x559
created by github.com/syncthing/syncthing/lib/model.NewModel
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/model/model.go:163 +0x980

### Version Information

   Syncthing Version: v0.14.26

**Comment by imsodin** [comment]
You have a folder in your config, which does not have an ID (or an empty one), so it panics. Syncthing itself didn't do that, that must have been added manually so you will also have to resolve it manually, i.e. edit the config and remove that folder or add its correct ID if you know it.

**Comment by kreddy0404** [comment]
Config does not have any empty id associated with any folder

**Comment by AudriusButkevicius** [comment]
Double check, as you might be thinking about labels, not ids.

**Comment by kreddy0404** [comment]
i did check for  folder id="" in config file

**Comment by imsodin** [comment]
Lets continue this in your thread in the forum: https://forum.syncthing.net/t/panic-cannot-add-empty-folder-id/11201

**Comment by kreddy0404** [comment]
ok thank you
