### ISSUE TITLE
Pre-launch check failures

### ISSUE THREAD

**Issue by AudriusButkevicius** [syncthing/syncthing-android#1084]
```
05-09 19:42:08.759: E/AndroidRuntime(17255): FATAL EXCEPTION: Thread-1131
05-09 19:42:08.759: E/AndroidRuntime(17255): Process: com.nutomic.syncthingandroid, PID: 17255
05-09 19:42:08.759: E/AndroidRuntime(17255): android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6530)
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:900)
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at android.view.View.requestLayout(View.java:17290)
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at android.view.View.requestLayout(View.java:17290)
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at android.view.View.requestLayout(View.java:17290)
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at android.view.View.requestLayout(View.java:17290)
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at android.view.View.requestLayout(View.java:17290)
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at android.view.View.requestLayout(View.java:17290)
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at android.view.View.requestLayout(View.java:17290)
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at android.widget.AbsListView.requestLayout(AbsListView.java:1985)
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at android.widget.AdapterView$AdapterDataSetObserver.onChanged(AdapterView.java:821)
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at android.widget.AbsListView$AdapterDataSetObserver.onChanged(AbsListView.java:6189)
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at android.database.DataSetObservable.notifyChanged(DataSetObservable.java:37)
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at android.widget.BaseAdapter.notifyDataSetChanged(BaseAdapter.java:50)
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at android.preference.PreferenceGroupAdapter.onPreferenceChange(PreferenceGroupAdapter.java:271)
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at android.preference.Preference.notifyChanged(Preference.java:1136)
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at android.preference.Preference.setEnabled(Preference.java:759)
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at com.nutomic.syncthingandroid.activities.SettingsActivity$SettingsFragment.onApiChange(SettingsActivity.java:265)
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at com.nutomic.syncthingandroid.service.SyncthingService.onApiChange(SyncthingService.java:367)
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at com.nutomic.syncthingandroid.service.SyncthingService.access$000(SyncthingService.java:34)
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at com.nutomic.syncthingandroid.service.SyncthingService$StartupTask.<init>(SyncthingService.java:196)
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at com.nutomic.syncthingandroid.service.SyncthingService.lambda$onStartCommand$0$SyncthingService(SyncthingService.java:126)
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at com.nutomic.syncthingandroid.service.SyncthingService$$Lambda$0.onKilled(Unknown Source)
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at com.nutomic.syncthingandroid.service.SyncthingRunnable.lambda$killSyncthing$0$SyncthingRunnable(SyncthingRunnable.java:292)
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at com.nutomic.syncthingandroid.service.SyncthingRunnable$$Lambda$0.run(Unknown Source)
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at java.lang.Thread.run(Thread.java:831)
```

**Comment by Catfriend1** [comment]
Link to release apk? Any reproducer or does this always occur?

**Comment by AudriusButkevicius** [comment]
Google just reported this as the release APK was uploaded.
There are a ton of other common exceptions in the store reports. 

If you are interested, I guess I can add you as a reader for the store exceptions.

**Comment by Catfriend1** [comment]
Sure, I can take a look at the reports. Maybe @Nutomic knows if some exceptions were there in older releases. I'd be interested if some new problems came up.

**Comment by AudriusButkevicius** [comment]
They are from older releases, but I am sure your code will trip on the same problem.

**Comment by AudriusButkevicius** [comment]
So I've added myself as a developer and then discarded the community account credentials which allows me to add new users :(. Perhaps @calmh will give me the creds again.

I've exported the crashes for April, and it mostly comes down to:

```
Package Name,Crash Report Date And Time,Crash Report Millis Since Epoch,Device,Android OS Version,App Version Name,App Version Code,Exception Class Name,Exception Message,Throwing File Name,Throwing Class Name,Throwing Method Name,Throwing Line Number,Native Crash Library,Native Crash Location,Crash Link
com.nutomic.syncthingandroid,2018-04-03T22:38:10Z,1522795090861,angler,27,0.10.6,4139,java.lang.NullPointerException,Attempt to read from field 'java.util.LinkedList$Node java.util.LinkedList$Node.next' on a null object reference,LinkedList.java,java.util.LinkedList$ListItr,next,893,,,https://play.google.com/apps/publish?dev_acc=00000000000000000000#ErrorClusterDetailsPlace:p=com.nutomic.syncthingandroid&lr=LAST_6_MONTHS&sh=false&s=new_status_desc&ed=1522795090861&et=CRASH&ecn=java.lang.NullPointerException&tf=LinkedList.java&tc=java.util.LinkedList$ListItr&tm=next
com.nutomic.syncthingandroid,2018-04-04T17:58:46Z,1522864726782,NB1,27,0.10.6,4139,java.lang.NullPointerException,Attempt to read from field 'com.nutomic.syncthingandroid.model.Config$Gui com.nutomic.syncthingandroid.model.Config.gui' on a null object reference,RestApi.java,com.nutomic.syncthingandroid.service.RestApi,getGui,312,,,https://play.google.com/apps/publish?dev_acc=00000000000000000000#ErrorClusterDetailsPlace:p=com.nutomic.syncthingandroid&lr=LAST_6_MONTHS&sh=false&s=new_status_desc&ed=1522864726782&et=CRASH&ecn=java.lang.NullPointerException&tf=RestApi.java&tc=com.nutomic.syncthingandroid.service.RestApi&tm=getGui
com.nutomic.syncthingandroid,2018-04-09T22:39:26Z,1523313566317,angler,27,0.10.6,4139,java.lang.NullPointerException,Attempt to read from field 'java.util.List com.nutomic.syncthingandroid.model.Config.folders' on a null object reference,RestApi.java,com.nutomic.syncthingandroid.service.RestApi,getFolders,218,,,https://play.google.com/apps/publish?dev_acc=00000000000000000000#ErrorClusterDetailsPlace:p=com.nutomic.syncthingandroid&lr=LAST_6_MONTHS&sh=false&s=new_status_desc&ed=1523313566317&et=CRASH&ecn=java.lang.NullPointerException&tf=RestApi.java&tc=com.nutomic.syncthingandroid.service.RestApi&tm=getFolders
com.nutomic.syncthingandroid,2018-04-10T17:05:27Z,1523379927445,B8000,19,0.10.6,4139,java.lang.NullPointerException,,RestApi.java,com.nutomic.syncthingandroid.service.RestApi,getFolders,218,,,https://play.google.com/apps/publish?dev_acc=00000000000000000000#ErrorClusterDetailsPlace:p=com.nutomic.syncthingandroid&lr=LAST_6_MONTHS&sh=false&s=new_status_desc&ed=1523379927445&et=CRASH&ecn=java.lang.NullPointerException&tf=RestApi.java&tc=com.nutomic.syncthingandroid.service.RestApi&tm=getFolders
com.nutomic.syncthingandroid,2018-04-12T08:31:00Z,1523521860039,sailfish,27,0.10.8,4141,java.lang.NumberFormatException,"For input string: """"",Integer.java,java.lang.Integer,parseInt,620,,,https://play.google.com/apps/publish?dev_acc=00000000000000000000#ErrorClusterDetailsPlace:p=com.nutomic.syncthingandroid&lr=LAST_6_MONTHS&sh=false&s=new_status_desc&ed=1523521860039&et=CRASH&ecn=java.lang.NumberFormatException&tf=Integer.java&tc=java.lang.Integer&tm=parseInt
com.nutomic.syncthingandroid,2018-04-12T08:32:04Z,1523521924074,sailfish,27,0.10.8,4141,java.lang.NumberFormatException,"For input string: """"",Integer.java,java.lang.Integer,parseInt,620,,,https://play.google.com/apps/publish?dev_acc=00000000000000000000#ErrorClusterDetailsPlace:p=com.nutomic.syncthingandroid&lr=LAST_6_MONTHS&sh=false&s=new_status_desc&ed=1523521924074&et=CRASH&ecn=java.lang.NumberFormatException&tf=Integer.java&tc=java.lang.Integer&tm=parseInt
com.nutomic.syncthingandroid,2018-04-12T20:46:34Z,1523565994867,sanders,25,0.10.8,4141,java.lang.NullPointerException,Attempt to read from field 'java.util.List com.nutomic.syncthingandroid.model.Config.folders' on a null object reference,RestApi.java,com.nutomic.syncthingandroid.service.RestApi,getFolders,218,,,https://play.google.com/apps/publish?dev_acc=00000000000000000000#ErrorClusterDetailsPlace:p=com.nutomic.syncthingandroid&lr=LAST_6_MONTHS&sh=false&s=new_status_desc&ed=1523565994867&et=CRASH&ecn=java.lang.NullPointerException&tf=RestApi.java&tc=com.nutomic.syncthingandroid.service.RestApi&tm=getFolders
com.nutomic.syncthingandroid,2018-04-13T10:11:54Z,1523614314752,marlin,27,0.10.8,4141,java.lang.NullPointerException,Attempt to read from field 'java.util.List com.nutomic.syncthingandroid.model.Config.folders' on a null object reference,RestApi.java,com.nutomic.syncthingandroid.service.RestApi,getFolders,218,,,https://play.google.com/apps/publish?dev_acc=00000000000000000000#ErrorClusterDetailsPlace:p=com.nutomic.syncthingandroid&lr=LAST_6_MONTHS&sh=false&s=new_status_desc&ed=1523614314752&et=CRASH&ecn=java.lang.NullPointerException&tf=RestApi.java&tc=com.nutomic.syncthingandroid.service.RestApi&tm=getFolders
com.nutomic.syncthingandroid,2018-04-14T09:51:00Z,1523699460420,A0001,25,0.10.8,4141,android.os.FileUriExposedException,file:///storage/emulated/0/DCIM exposed beyond app through Intent.getData(),StrictMode.java,android.os.StrictMode,onFileUriExposed,1806,,,https://play.google.com/apps/publish?dev_acc=00000000000000000000#ErrorClusterDetailsPlace:p=com.nutomic.syncthingandroid&lr=LAST_6_MONTHS&sh=false&s=new_status_desc&ed=1523699460420&et=CRASH&ecn=android.os.FileUriExposedException&tf=StrictMode.java&tc=android.os.StrictMode&tm=onFileUriExposed
com.nutomic.syncthingandroid,2018-04-14T12:26:01Z,1523708761719,taimen,27,0.10.6,4139,java.lang.NullPointerException,Attempt to read from field 'java.util.List com.nutomic.syncthingandroid.model.Config.folders' on a null object reference,RestApi.java,com.nutomic.syncthingandroid.service.RestApi,getFolders,218,,,https://play.google.com/apps/publish?dev_acc=00000000000000000000#ErrorClusterDetailsPlace:p=com.nutomic.syncthingandroid&lr=LAST_6_MONTHS&sh=false&s=new_status_desc&ed=1523708761719&et=CRASH&ecn=java.lang.NullPointerException&tf=RestApi.java&tc=com.nutomic.syncthingandroid.service.RestApi&tm=getFolders
com.nutomic.syncthingandroid,2018-04-17T23:10:05Z,1524006605259,sailfish,27,0.10.3,4136,java.lang.NullPointerException,Attempt to read from field 'com.nutomic.syncthingandroid.model.Options com.nutomic.syncthingandroid.model.Config.options' on a null object reference,RestApi.java,com.nutomic.syncthingandroid.service.RestApi,getOptions,308,,,https://play.google.com/apps/publish?dev_acc=00000000000000000000#ErrorClusterDetailsPlace:p=com.nutomic.syncthingandroid&lr=LAST_6_MONTHS&sh=false&s=new_status_desc&ed=1524006605259&et=CRASH&ecn=java.lang.NullPointerException&tf=RestApi.java&tc=com.nutomic.syncthingandroid.service.RestApi&tm=getOptions
com.nutomic.syncthingandroid,2018-04-18T08:51:10Z,1524041470706,A0001,25,0.10.8,4141,java.lang.NullPointerException,Attempt to read from field 'java.util.List com.nutomic.syncthingandroid.model.Config.folders' on a null object reference,RestApi.java,com.nutomic.syncthingandroid.service.RestApi,getFolders,218,,,https://play.google.com/apps/publish?dev_acc=00000000000000000000#ErrorClusterDetailsPlace:p=com.nutomic.syncthingandroid&lr=LAST_6_MONTHS&sh=false&s=new_status_desc&ed=1524041470706&et=CRASH&ecn=java.lang.NullPointerException&tf=RestApi.java&tc=com.nutomic.syncthingandroid.service.RestApi&tm=getFolders
com.nutomic.syncthingandroid,2018-04-21T18:21:12Z,1524334872579,angler,27,0.10.8,4141,java.lang.NullPointerException,Attempt to read from field 'com.nutomic.syncthingandroid.model.Config$Gui com.nutomic.syncthingandroid.model.Config.gui' on a null object reference,RestApi.java,com.nutomic.syncthingandroid.service.RestApi,getGui,312,,,https://play.google.com/apps/publish?dev_acc=00000000000000000000#ErrorClusterDetailsPlace:p=com.nutomic.syncthingandroid&lr=LAST_6_MONTHS&sh=false&s=new_status_desc&ed=1524334872579&et=CRASH&ecn=java.lang.NullPointerException&tf=RestApi.java&tc=com.nutomic.syncthingandroid.service.RestApi&tm=getGui
com.nutomic.syncthingandroid,2018-04-21T21:19:08Z,1524345548147,montana_n,25,0.10.8,4141,java.util.ConcurrentModificationException,Unable to start service com.nutomic.syncthingandroid.service.SyncthingService@24d5078 with Intent { act=com.nutomic.syncthingandroid.service.SyncthingService.RESTART cmp=com.nutomic.syncthingandroid/.service.SyncthingService }: java.util.ConcurrentModificationException,LinkedList.java,java.util.LinkedList$ListItr,checkForComodification,967,,,https://play.google.com/apps/publish?dev_acc=00000000000000000000#ErrorClusterDetailsPlace:p=com.nutomic.syncthingandroid&lr=LAST_6_MONTHS&sh=false&s=new_status_desc&ed=1524345548147&et=CRASH&ecn=java.util.ConcurrentModificationException&tf=LinkedList.java&tc=java.util.LinkedList$ListItr&tm=checkForComodification
com.nutomic.syncthingandroid,2018-04-25T02:07:53Z,1524622073738,hero2qltechn,24,0.10.6,4139,java.lang.NullPointerException,Attempt to read from field 'java.util.List com.nutomic.syncthingandroid.model.Config.folders' on a null object reference,RestApi.java,com.nutomic.syncthingandroid.service.RestApi,getFolders,218,,,https://play.google.com/apps/publish?dev_acc=00000000000000000000#ErrorClusterDetailsPlace:p=com.nutomic.syncthingandroid&lr=LAST_6_MONTHS&sh=false&s=new_status_desc&ed=1524622073738&et=CRASH&ecn=java.lang.NullPointerException&tf=RestApi.java&tc=com.nutomic.syncthingandroid.service.RestApi&tm=getFolders
com.nutomic.syncthingandroid,2018-04-26T14:07:27Z,1524751647114,ASUS_Z012D,26,0.10.8,4141,java.lang.NullPointerException,Attempt to read from field 'java.lang.String com.nutomic.syncthingandroid.model.Folder.path' on a null object reference,ShareActivity.java,com.nutomic.syncthingandroid.activities.ShareActivity,lambda$onCreate$1$ShareActivity,170,,,https://play.google.com/apps/publish?dev_acc=00000000000000000000#ErrorClusterDetailsPlace:p=com.nutomic.syncthingandroid&lr=LAST_6_MONTHS&sh=false&s=new_status_desc&ed=1524751647114&et=CRASH&ecn=java.lang.NullPointerException&tf=ShareActivity.java&tc=com.nutomic.syncthingandroid.activities.ShareActivity&tm=lambda$onCreate$1$ShareActivity
com.nutomic.syncthingandroid,2018-04-29T03:14:35Z,1524971675077,bullhead,27,0.10.8,4141,java.lang.NullPointerException,Attempt to read from field 'java.util.List com.nutomic.syncthingandroid.model.Config.folders' on a null object reference,RestApi.java,com.nutomic.syncthingandroid.service.RestApi,getFolders,218,,,https://play.google.com/apps/publish?dev_acc=00000000000000000000#ErrorClusterDetailsPlace:p=com.nutomic.syncthingandroid&lr=LAST_6_MONTHS&sh=false&s=new_status_desc&ed=1524971675077&et=CRASH&ecn=java.lang.NullPointerException&tf=RestApi.java&tc=com.nutomic.syncthingandroid.service.RestApi&tm=getFolders
```

**Comment by AudriusButkevicius** [comment]
@Catfriend1 do you have a google friendly email account?

**Comment by Nutomic** [comment]
@AudriusButkevicius Would be useful if you can add me as well. Does it require a Google Email?

**Comment by AudriusButkevicius** [comment]
Not sure. I think it needs a google login.

**Comment by Catfriend1** [comment]
@AudriusButkevicius I've sent you an email so you can add me by google mail.

**Comment by calmh** [comment]
@AudriusButkevicius I'm not sure what you want me to do. I logged in and took a look and I see you on the account as "release manager" which I guess is less than admin somehow? Do you still have the "original" credentials for the Syncthing account I gave you? If so feel free to use them to upgrade yourself to whatever level possible

**Comment by AudriusButkevicius** [comment]
I think I've invited both of you.

**Comment by Catfriend1** [comment]
Thanks, I'll go through the reports as soon as I've time

**Comment by Catfriend1** [comment]
Thats no good news, I wonder how long microg gms will work as the last ban happened 2014 and after complaining about gmail access lost I got unlocked and have three years of continously working microg stuff... Google is often free but not for nothing in return.

**Comment by Nutomic** [comment]
I haven't used any Google services in years, except for Syncthing releases. So I really don't care. Microg also works without any account.
