### ISSUE TITLE
Native binary crash

### ISSUE THREAD

**Issue by Catfriend1** [syncthing/syncthing-android#1174]
Hi together!

I had syncthing 0.10.11 running fine since it got released fine and I did not do any major changes to my android installation. (running as root, run in background is disabled)
Today I found the wrapper's UI showing "Scanning" on all folders after starting the app (as usual) from the home screen. Waiting for 5 minutes didn't show any UI change, trying to open the web UI said "connected refused on port localhost:web_ui_port". I opened OSMonitor and saw that libsyncthing.so was no longer running. I exited the app and restarted it from home screen and syncthing worked fine again and fully synced all folder within 2 minutes (about 40 Megs were changed). I had enough RAM free (as I can see from OSMonitor, LG G4 has 3 GByte of memory installed).
Opening MatLog after the app restart (where syncthing binary worked again correctly) I saw some last bits of the error lines from the initially mentioned problem. Reconstructing what has happened, syncthing app came up fine, service started the libsyncthing.so binary and then the native binary's process died with the attached error (maybe some lines from the beginning are missing due to android log buffer rotation which already happened until I got into the logcat reader app).
@imsodin: I can't reproduce this but I suspect some upstream error?! Unfortunately I can't reproduce the problem now. Maybe something related to the "Index out of bounds" issue on upstream repo?

Thanks for your feedback. If we don't get the point, I'll close the ticket after some days waiting and wait for 0.14.49 to be released.

Log attached:
[2018-06-28-11-44-52_android_log_native_maybe_beginning_missed.zip](https://github.com/syncthing/syncthing-android/files/2145562/2018-06-28-11-44-52_android_log_native_maybe_beginning_missed.zip)

Maybe related to the symptoms described in #1172

    App Version: 0.10.11
    Syncthing Version: v0.14.48 (this seems relevant)
    Android Version: Android 7.1.2, LineAgeOS 14.1, device lg-h815

> 06-28 11:43:10.581 W/SyncthingNativeCode(19839): created by github.com/syncthing/syncthing/vendor/github.com/rcrowley/go-metrics.NewMeter
06-28 11:43:10.581 W/SyncthingNativeCode(19839): 	/opt/buildagent/work/31d51f290561a759/syncthing/src/github.com/syncthing/syncthing/vendor/github.com/rcrowley/go-metrics/meter.go:44 +0x104
06-28 11:43:10.582 W/SyncthingNativeCode(19839): 
06-28 11:43:10.582 W/SyncthingNativeCode(19839): goroutine 68 [IO wait]:
06-28 11:43:10.582 W/SyncthingNativeCode(19839): internal/poll.runtime_pollWait(0x7f7f6c7df0, 0x72, 0x0)
06-28 11:43:10.582 W/SyncthingNativeCode(19839): 	/opt/go/src/runtime/netpoll.go:173 +0x3c
06-28 11:43:10.582 W/SyncthingNativeCode(19839): internal/poll.(*pollDesc).wait(0x442040c198, 0x72, 0xffffffffffffff00, 0x555af20be0, 0x555af1ada0)
06-28 11:43:10.583 W/SyncthingNativeCode(19839): 	/opt/go/src/internal/poll/fd_poll_runtime.go:85 +0xa0
06-28 11:43:10.583 W/SyncthingNativeCode(19839): internal/poll.(*pollDesc).waitRead(0x442040c198, 0x4421678c00, 0x400, 0x400)
06-28 11:43:10.583 W/SyncthingNativeCode(19839): 	/opt/go/src/internal/poll/fd_poll_runtime.go:90 +0x30
06-28 11:43:10.583 W/SyncthingNativeCode(19839): internal/poll.(*FD).Read(0x442040c180, 0x4421678c00, 0x400, 0x400, 0x0, 0x0, 0x0)
06-28 11:43:10.584 W/SyncthingNativeCode(19839): 	/opt/go/src/internal/poll/fd_unix.go:126 +0x138
06-28 11:43:10.584 W/SyncthingNativeCode(19839): net.(*netFD).Read(0x442040c180, 0x4421678c00, 0x400, 0x400, 0xff3, 0x555a232020, 0x40)
06-28 11:43:10.584 W/SyncthingNativeCode(19839): 	/opt/go/src/net/fd_unix.go:202 +0x3c
06-28 11:43:10.584 W/SyncthingNativeCode(19839): net.(*conn).Read(0x4421770000, 0x4421678c00, 0x400, 0x400, 0x0, 0x0, 0x0)
06-28 11:43:10.584 W/SyncthingNativeCode(19839): 	/opt/go/src/net/net.go:176 +0x50
06-28 11:43:10.584 W/SyncthingNativeCode(19839): github.com/syncthing/syncthing/lib/tlsutil.(*UnionedConnection).Read(0x44211be0e0, 0x4421678c00, 0x400, 0x400, 0x442040c100, 0x7f7f333080, 0x60f)
06-28 11:43:10.585 W/SyncthingNativeCode(19839): 	/opt/buildagent/work/31d51f290561a759/syncthing/src/github.com/syncthing/syncthing/lib/tlsutil/tlsutil.go:160 +0xb0
06-28 11:43:10.585 W/SyncthingNativeCode(19839): crypto/tls.(*block).readFromUntil(0x442028d9b0, 0x7f7f333080, 0x44211be0e0, 0x5, 0x44211be0e0, 0x555a3752cc)
06-28 11:43:10.585 W/SyncthingNativeCode(19839): 	/opt/go/src/crypto/tls/conn.go:488 +0x7c
06-28 11:43:10.585 W/SyncthingNativeCode(19839): crypto/tls.(*Conn).readRecord(0x4420f56700, 0x555ac1b017, 0x4420f56820, 0x40543dff4)
06-28 11:43:10.586 W/SyncthingNativeCode(19839): 	/opt/go/src/crypto/tls/conn.go:590 +0xa0
06-28 11:43:10.586 W/SyncthingNativeCode(19839): crypto/tls.(*Conn).Read(0x4420f56700, 0x44217fa000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
06-28 11:43:10.587 W/SyncthingNativeCode(19839): 	/opt/go/src/crypto/tls/conn.go:1134 +0xbc
06-28 11:43:10.587 W/SyncthingNativeCode(19839): net/http.(*connReader).Read(0x442028dad0, 0x44217fa000, 0x1000, 0x1000, 0x0, 0x0, 0x955c7431ddcc)
06-28 11:43:10.587 W/SyncthingNativeCode(19839): 	/opt/go/src/net/http/server.go:753 +0xd0
06-28 11:43:10.587 W/SyncthingNativeCode(19839): bufio.(*Reader).fill(0x44207c8a80)
06-28 11:43:10.588 W/SyncthingNativeCode(19839): 	/opt/go/src/bufio/bufio.go:97 +0x104
06-28 11:43:10.588 W/SyncthingNativeCode(19839): bufio.(*Reader).Peek(0x44207c8a80, 0x4, 0x40543dff4, 0x555af66ae0, 0x0, 0x0, 0x555af66ae0)
06-28 11:43:10.591 W/SyncthingNativeCode(19839): 	/opt/go/src/bufio/bufio.go:129 +0x2c
06-28 11:43:10.591 W/SyncthingNativeCode(19839): net/http.(*conn).serve(0x44200a2960, 0x555af26260, 0x4421581700)
06-28 11:43:10.592 W/SyncthingNativeCode(19839): 	/opt/go/src/net/http/server.go:1826 +0x690
06-28 11:43:10.592 W/SyncthingNativeCode(19839): created by net/http.(*Server).Serve
06-28 11:43:10.592 W/SyncthingNativeCode(19839): 	/opt/go/src/net/http/server.go:2720 +0x204
06-28 11:43:10.592 W/SyncthingNativeCode(19839): 
06-28 11:43:10.592 W/SyncthingNativeCode(19839): goroutine 130 [select]:
06-28 11:43:10.592 W/SyncthingNativeCode(19839): github.com/syncthing/syncthing/lib/protocol.(*rawConnection).pingReceiver(0x4421984540)
06-28 11:43:10.593 W/SyncthingNativeCode(19839): 	/opt/buildagent/work/31d51f290561a759/syncthing/src/github.com/syncthing/syncthing/lib/protocol/protocol.go:857 +0xfc
06-28 11:43:10.594 W/SyncthingNativeCode(19839): created by github.com/syncthing/syncthing/lib/protocol.(*rawConnection).Start
06-28 11:43:10.594 W/SyncthingNativeCode(19839): 	/opt/buildagent/work/31d51f290561a759/syncthing/src/github.com/syncthing/syncthing/lib/protocol/protocol.go:213 +0x94
06-28 11:43:10.594 W/SyncthingNativeCode(19839): 
06-28 11:43:10.594 W/SyncthingNativeCode(19839): goroutine 131 [select]:
06-28 11:43:10.594 W/SyncthingNativeCode(19839): github.com/syncthing/syncthing/lib/events.(*Subscription).Poll(0x44200fb420, 0xdf8475800, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
06-28 11:43:10.594 W/SyncthingNativeCode(19839): 	/opt/buildagent/work/31d51f290561a759/syncthing/src/github.com/syncthing/syncthing/lib/events/events.go:339 +0x18c
06-28 11:43:10.595 W/SyncthingNativeCode(19839): github.com/syncthing/syncthing/lib/model.sendIndexes(0x7f7f6dd328, 0x44206d7170, 0x44202f4510, 0xb, 0x4420010460, 0x44221a0090, 0xad7, 0x4420152200, 0x2f, 0x442032be00)
06-28 11:43:10.595 W/SyncthingNativeCode(19839): 	/opt/buildagent/work/31d51f290561a759/syncthing/src/github.com/syncthing/syncthing/lib/model/model.go:1725 +0x41c
06-28 11:43:10.595 W/SyncthingNativeCode(19839): created by github.com/syncthing/syncthing/lib/model.(*Model).ClusterConfig
06-28 11:43:10.595 W/SyncthingNativeCode(19839): 	/opt/buildagent/work/31d51f290561a759/syncthing/src/github.com/syncthing/syncthing/lib/model/model.go:1036 +0xf48
06-28 11:43:10.595 W/SyncthingNativeCode(19839): 
06-28 11:43:10.596 W/SyncthingNativeCode(19839): goroutine 132 [select]:
06-28 11:43:10.596 W/SyncthingNativeCode(19839): github.com/syncthing/syncthing/lib/events.(*Subscription).Poll(0x44200fb5a0, 0xdf8475800, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
06-28 11:43:10.596 W/SyncthingNativeCode(19839): 	/opt/buildagent/work/31d51f290561a759/syncthing/src/github.com/syncthing/syncthing/lib/events/events.go:339 +0x18c
06-28 11:43:10.596 W/SyncthingNativeCode(19839): github.com/syncthing/syncthing/lib/model.sendIndexes(0x7f7f6dd328, 0x44206d7170, 0x44202f4550, 0xb, 0x4420011cc0, 0x44221a02d0, 0x14ba, 0x4420152200, 0x2f, 0x442032bf00)
06-28 11:43:10.597 W/SyncthingNativeCode(19839): 	/opt/buildagent/work/31d51f290561a759/syncthing/src/github.com/syncthing/syncthing/lib/model/model.go:1725 +0x41c
06-28 11:43:10.597 W/SyncthingNativeCode(19839): created by github.com/syncthing/syncthing/lib/model.(*Model).ClusterConfig
06-28 11:43:10.599 W/SyncthingNativeCode(19839): 	/opt/buildagent/work/31d51f290561a759/syncthing/src/github.com/syncthing/syncthing/lib/model/model.go:1036 +0xf48

**Comment by Catfriend1** [comment]
Yeah I wish I could go into the past and grab it but was too late :(
