### ISSUE TITLE
TypeError crash when backing out of Web GUI

### ISSUE THREAD

**Issue by ProactiveServices** [syncthing/syncthing-android#1216]
### Version Information
    App Version: 0.10.13
    Syncthing Version: v0.14.49-dirty
    Android Version: Android 5.0.2

In the Web GUI I opened a Share's settings and then used the back icon, top left, to back out of the Web GUI and Syncthing crashed. The Syncthing log was reset upon restart.

> --------- beginning of main
> 08-12 19:37:36.564 I/Choreographer(16825): Skipped 37 frames!  The application may be doing too much work on its main thread.
> 08-12 19:37:37.555 W/KeyCharacterMap(16825): Load KCM of non-default device may incur unexpected result. Device ID:9
> 08-12 19:37:40.909 I/Choreographer(16825): Skipped 261 frames!  The application may be doing too much work on its main thread.
> 08-12 19:37:41.920 W/cr_AwContents(16825): WebView.destroy() called while WebView is still attached to window.
> 08-12 19:37:44.583 E/StrictMode(16825): class com.nutomic.syncthingandroid.activities.WebGuiActivity; instances=2; limit=1
> 08-12 19:37:44.583 E/StrictMode(16825): android.os.StrictMode$InstanceCountViolation: class com.nutomic.syncthingandroid.activities.WebGuiActivity; instances=2; limit=1
> 08-12 19:37:44.583 E/StrictMode(16825): 	at android.os.StrictMode.setClassInstanceLimit(StrictMode.java:1)
> 08-12 19:37:44.593 I/Choreographer(16825): Skipped 183 frames!  The application may be doing too much work on its main thread.
> 08-12 19:37:45.974 E/cr_WebContentsImpl(16825): UserDataMap can't be found
> 08-12 19:37:46.014 I/Choreographer(16825): Skipped 84 frames!  The application may be doing too much work on its main thread.
> 08-12 19:37:46.865 I/EventProcessor(16825): Rescanned file via MediaScanner: /storage/emulated/0/redacted
> 08-12 19:37:46.945 I/EventProcessor(16825): Rescanned file via MediaScanner: /storage/emulated/0/redacted
> 08-12 19:37:46.975 I/EventProcessor(16825): Rescanned file via MediaScanner: /storage/emulated/0/redacted
> 08-12 19:37:47.046 I/EventProcessor(16825): Rescanned file via MediaScanner: /storage/emulated/0/redacted
> 08-12 19:37:47.096 I/EventProcessor(16825): Rescanned file via MediaScanner: /storage/emulated/0/redacted
> 08-12 19:37:47.186 I/EventProcessor(16825): Rescanned file via MediaScanner: /storage/emulated/0/redacted
> 08-12 19:37:47.236 I/EventProcessor(16825): Rescanned file via MediaScanner: /storage/emulated/0/redacted
> 08-12 19:37:47.286 I/EventProcessor(16825): Rescanned file via MediaScanner: /storage/emulated/0/redacted
> 08-12 19:37:47.346 I/EventProcessor(16825): Rescanned file via MediaScanner: /storage/emulated/0/redacted
> 08-12 19:38:02.432 I/EventProcessor(16825): Rescanned file via MediaScanner: /storage/emulated/0/redacted
> 08-12 19:38:07.668 I/SyncthingNativeCode(16825): [YECXW] INFO: Connection to IGHCPN5-ZCKFYSK-XYUJ3PW-ZZTXAXC-YA254S7-IINUXD3-T6PLLOF-FPKLOAL at 192.168.150.10:35000-192.168.150.17:1349/tcp-server closed: reading length: EOF
> 08-12 19:38:12.112 I/ConfigXml(16825): Loaded Syncthing config file
> 08-12 19:38:13.093 I/Choreographer(16825): Skipped 31 frames!  The application may be doing too much work on its main thread.
> 08-12 19:38:19.110 I/chromium(16825): [INFO:CONSOLE(11)] "TypeError: Cannot read property '$name' of undefined
> 08-12 19:38:19.110 I/chromium(16825):     at ChildScope.$scope.loadFormIntoScope (https://127.0.0.1:8384/syncthing/core/syncthingController.js:1545:50)
> 08-12 19:38:19.110 I/chromium(16825):     at $parseFunctionCall (https://127.0.0.1:8384/vendor/angular/angular.js:12493:18)
> 08-12 19:38:19.110 I/chromium(16825):     at ChildScope.$eval (https://127.0.0.1:8384/vendor/angular/angular.js:14589:28)
> 08-12 19:38:19.110 I/chromium(16825):     at pre (https://127.0.0.1:8384/vendor/angular/angular.js:22621:15)
> 08-12 19:38:19.110 I/chromium(16825):     at invokeLinkFn (https://127.0.0.1:8384/vendor/angular/angular.js:8300:9)
> 08-12 19:38:19.110 I/chromium(16825):     at nodeLinkFn (https://127.0.0.1:8384/vendor/angular/angular.js:7789:11)
> 08-12 19:38:19.110 I/chromium(16825):     at compositeLinkFn (https://127.0.0.1:8384/vendor/angular/angular.js:7159:13)
> 08-12 19:38:19.110 I/chromium(16825):     at nodeLinkFn (https://127.0.0.1:8384/vendor/angular/angular.js:7805:24)
> 08-12 19:38:19.110 I/chromium(16825):     at compositeLinkFn (https://127.0.0.1:8384/vendor/angular/angular.js:7159:13)
> 08-12 19:38:19.110 I/chromium(16825):     at compositeLinkFn (https://127.0.0.1:8384/vendor/angular/angular.js:7162:13)", source: https://127.0.0.1:8384/syncthing/development/logbar.js (11)
> 08-12 19:38:19.110 I/chromium(16825): [INFO:CONSOLE(1545)] "loadFormIntoScope", source: https://127.0.0.1:8384/syncthing/core/syncthingController.js (1545)
> 08-12 19:38:19.250 I/chromium(16825): [INFO:CONSOLE(1545)] "loadFormIntoScope", source: https://127.0.0.1:8384/syncthing/core/syncthingController.js (1545)
> 08-12 19:38:20.942 I/chromium(16825): [INFO:CONSOLE(116)] "UIOnline", source: https://127.0.0.1:8384/syncthing/core/syncthingController.js (116)
> 08-12 19:38:21.202 I/chromium(16825): [INFO:CONSOLE(438)] "refreshSystem", source: https://127.0.0.1:8384/syncthing/core/syncthingController.js (438)
> 08-12 19:38:21.202 I/chromium(16825): [INFO:CONSOLE(454)] "refreshDiscoveryCache", source: https://127.0.0.1:8384/syncthing/core/syncthingController.js (454)
> 08-12 19:38:21.212 I/chromium(16825): [INFO:CONSOLE(562)] "refreshConfig", source: https://127.0.0.1:8384/syncthing/core/syncthingController.js (562)
> 08-12 19:38:21.222 I/chromium(16825): [INFO:CONSOLE(548)] "refreshConnections", source: https://127.0.0.1:8384/syncthing/core/syncthingController.js (548)
> 08-12 19:38:21.222 I/chromium(16825): [INFO:CONSOLE(691)] "refreshDeviceStats", source: https://127.0.0.1:8384/syncthing/core/syncthingController.js (691)
> 08-12 19:38:21.222 I/chromium(16825): [INFO:CONSOLE(706)] "refreshfolderStats", source: https://127.0.0.1:8384/syncthing/core/syncthingController.js (706)
> 08-12 19:38:21.222 I/chromium(16825): [INFO:CONSOLE(720)] "refreshGlobalChanges", source: https://127.0.0.1:8384/syncthing/core/syncthingController.js (720)
> 08-12 19:38:24.616 I/chromium(16825): [INFO:CONSOLE(366)] "refreshFolder", source: https://127.0.0.1:8384/syncthing/core/syncthingController.js (366)
> 08-12 19:38:24.616 I/chromium(16825): [INFO:CONSOLE(500)] "recalcCompletion", source: https://127.0.0.1:8384/syncthing/core/syncthingController.js (500)
> 08-12 19:38:24.616 I/chromium(16825): [INFO:CONSOLE(500)] "recalcCompletion", source: https://127.0.0.1:8384/syncthing/core/syncthingController.js (500)
> 08-12 19:38:24.616 I/chromium(16825): [INFO:CONSOLE(500)] "recalcCompletion", source: https://127.0.0.1:8384/syncthing/core/syncthingController.js (500)
> 08-12 19:38:24.616 I/chromium(16825): [INFO:CONSOLE(366)] "refreshFolder", source: https://127.0.0.1:8384/syncthing/core/syncthingController.js (366)
> 08-12 19:38:24.616 I/chromium(16825): [INFO:CONSOLE(500)] "recalcCompletion", source: https://127.0.0.1:8384/syncthing/core/syncthingController.js (500)
> 08-12 19:38:24.616 I/chromium(16825): [INFO:CONSOLE(500)] "recalcCompletion", source: https://127.0.0.1:8384/syncthing/core/syncthingController.js (500)
> 08-12 19:38:24.616 I/chromium(16825): [INFO:CONSOLE(366)] "refreshFolder", source: https://127.0.0.1:8384/syncthing/core/syncthingController.js (366)
> 08-12 19:38:24.616 I/chromium(16825): [INFO:CONSOLE(500)] "recalcCompletion", source: https://127.0.0.1:8384/syncthing/core/syncthingController.js (500)
> 08-12 19:38:24.616 I/chromium(16825): [INFO:CONSOLE(500)] "recalcCompletion", source: https://127.0.0.1:8384/syncthing/core/syncthingController.js (500)
> 08-12 19:38:24.616 I/chromium(16825): [INFO:CONSOLE(366)] "refreshFolder", source: https://127.0.0.1:8384/syncthing/core/syncthingController.js (366)
> 08-12 19:38:24.626 I/chromium(16825): [INFO:CONSOLE(366)] "refreshFolder", source: https://127.0.0.1:8384/syncthing/core/syncthingController.js (366)
> 08-12 19:38:24.626 I/chromium(16825): [INFO:CONSOLE(500)] "recalcCompletion", source: https://127.0.0.1:8384/syncthing/core/syncthingController.js (500)
> 08-12 19:38:24.626 I/chromium(16825): [INFO:CONSOLE(500)] "recalcCompletion", source: https://127.0.0.1:8384/syncthing/core/syncthingController.js (500)
> 08-12 19:38:24.626 I/chromium(16825): [INFO:CONSOLE(366)] "refreshFolder", source: https://127.0.0.1:8384/syncthing/core/syncthingController.js (366)
> 08-12 19:38:24.626 I/chromium(16825): [INFO:CONSOLE(500)] "recalcCompletion", source: https://127.0.0.1:8384/syncthing/core/syncthingController.js (500)
> 08-12 19:38:24.626 I/chromium(16825): [INFO:CONSOLE(500)] "recalcCompletion", source: https://127.0.0.1:8384/syncthing/core/syncthingController.js (500)
> 08-12 19:38:24.626 I/chromium(16825): [INFO:CONSOLE(500)] "recalcCompletion", source: https://127.0.0.1:8384/syncthing/core/syncthingController.js (500)
> 08-12 19:38:24.626 I/chromium(16825): [INFO:CONSOLE(366)] "refreshFolder", source: https://127.0.0.1:8384/syncthing/core/syncthingController.js (366)
> 08-12 19:38:24.626 I/chromium(16825): [INFO:CONSOLE(366)] "refreshFolder", source: https://127.0.0.1:8384/syncthing/core/syncthingController.js (366)
> 08-12 19:38:24.656 I/chromium(16825): [INFO:CONSOLE(500)] "recalcCompletion", source: https://127.0.0.1:8384/syncthing/core/syncthingController.js (500)
> 08-12 19:38:24.656 I/chromium(16825): [INFO:CONSOLE(500)] "recalcCompletion", source: https://127.0.0.1:8384/syncthing/core/syncthingController.js (500)
> 08-12 19:38:24.656 I/chromium(16825): [INFO:CONSOLE(500)] "recalcCompletion", source: https://127.0.0.1:8384/syncthing/core/syncthingController.js (500)
> 08-12 19:38:24.656 I/chromium(16825): [INFO:CONSOLE(366)] "refreshFolder", source: https://127.0.0.1:8384/syncthing/core/syncthingController.js (366)
> 08-12 19:38:24.666 I/chromium(16825): [INFO:CONSOLE(500)] "recalcCompletion", source: https://127.0.0.1:8384/syncthing/core/syncthingController.js (500)
> 08-12 19:38:24.666 I/chromium(16825): [INFO:CONSOLE(500)] "recalcCompletion", source: https://127.0.0.1:8384/syncthing/core/syncthingController.js (500)
> 08-12 19:38:24.666 I/chromium(16825): [INFO:CONSOLE(500)] "recalcCompletion", source: https://127.0.0.1:8384/syncthing/core/syncthingController.js (500)
> 08-12 19:38:24.666 I/chromium(16825): [INFO:CONSOLE(366)] "refreshFolder", source: https://127.0.0.1:8384/syncthing/core/syncthingController.js (366)
> 08-12 19:38:24.666 I/chromium(16825): [INFO:CONSOLE(500)] "recalcCompletion", source: https://127.0.0.1:8384/syncthing/core/syncthingController.js (500)
> 08-12 19:38:24.666 I/chromium(16825): [INFO:CONSOLE(366)] "refreshFolder", source: https://127.0.0.1:8384/syncthing/core/syncthingController.js (366)
> 08-12 19:38:24.666 I/chromium(16825): [INFO:CONSOLE(500)] "recalcCompletion", source: https://127.0.0.1:8384/syncthing/core/syncthingController.js (500)
> 08-12 19:38:24.666 I/chromium(16825): [INFO:CONSOLE(500)] "recalcCompletion", source: https://127.0.0.1:8384/syncthing/core/syncthingController.js (500)
> 08-12 19:38:24.666 I/chromium(16825): [INFO:CONSOLE(500)] "recalcCompletion", source: https://127.0.0.1:8384/syncthing/core/syncthingController.js (500)
> 08-12 19:38:24.666 I/chromium(16825): [INFO:CONSOLE(500)] "recalcCompletion", source: https://127.0.0.1:8384/syncthing/core/syncthingController.js (500)
> 08-12 19:38:24.666 I/chromium(16825): [INFO:CONSOLE(500)] "recalcCompletion", source: https://127.0.0.1:8384/syncthing/core/syncthingController.js (500)
> 08-12 19:38:25.446 W/cr_AwContents(16825): WebView.destroy() called while WebView is still attached to window.
> 08-12 19:38:25.837 E/StrictMode(16825): class com.nutomic.syncthingandroid.activities.WebGuiActivity; instances=3; limit=1
> 08-12 19:38:25.837 E/StrictMode(16825): android.os.StrictMode$InstanceCountViolation: class com.nutomic.syncthingandroid.activities.WebGuiActivity; instances=3; limit=1
> 08-12 19:38:25.837 E/StrictMode(16825): 	at android.os.StrictMode.setClassInstanceLimit(StrictMode.java:1)
> 08-12 19:38:30.592 I/System  (16825): exec(/system/bin/logcat -t 300 -v time -s SyncthingNativeCode @ com.nutomic.syncthingandroid.activities.LogActivity$UpdateLogTask.getLog:155)
> 08-12 19:38:35.697 I/System  (16825): exec(/system/bin/logcat -t 300 -v time *:i ps:s art:s @ com.nutomic.syncthingandroid.activities.LogActivity$UpdateLogTask.getLog:155)

**Comment by Catfriend1** [comment]
It's the chromium (system) app part that crashed not syncthing. Which chromium version are you on? Maybe we should a try-catch for older chromium's so the exception on destroy doesn't get shown. It would then come up (with a shared parent process reused instance) properly later if you reenter the web UI. Chromium is somehow specific as one app provides views for multiple "parent" apps.

**Comment by AudriusButkevicius** [comment]
The only error level messages I see is:
```
08-12 19:38:25.837 E/StrictMode(16825): android.os.StrictMode$InstanceCountViolation: class com.nutomic.syncthingandroid.activities.WebGuiActivity; instances=3; limit=1
```

**Comment by Catfriend1** [comment]
This always occurs and does not harm anything ;)

**Comment by ProactiveServices** [comment]
I can't find reference to a Chromium version on the phone, but the "Android System WebView" version is 68.0.3440.91, which looks like a Chromium-like version.

**Comment by AudriusButkevicius** [comment]
How do we know its chromium crashing?
