### ISSUE TITLE
Cannot compile on macOS

### ISSUE THREAD

**Issue by davidhq** [syncthing/syncthing-android#1218]
```
$ ./gradlew buildNative

> Configure project :app
Signing not ready. Did you specify a signingConfig for the variation Release?

> Task :syncthing:buildNative FAILED
Building for arm
Building syncthing
stat build.go: no such file or directory
Traceback (most recent call last):
  File "./build-syncthing.py", line 119, in <module>
    ] + pkg_argument + ['-no-upgrade', 'build'], env=environ, cwd=syncthing_dir)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['go', 'run', 'build.go', '-goos', 'android', '-goarch', 'arm', '-pkgdir', '/Users/david/Desktop/syncthing-android/syncthing/gobuild/go-packages/arm', '-no-upgrade', 'build']' returned non-zero exit status 1


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':syncthing:buildNative'.
> Process 'command 'python'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
1 actionable task: 1 executed
```

Any tips? Thank you

**Comment by davidhq** [comment]
I guess `build.go` script should be present? I don't have such file inside cloned repository...

**Comment by davidhq** [comment]
made a mistake, will open another one with correct info
