### ISSUE TITLE
Cannot compile on macOS

### ISSUE THREAD

**Issue by davidhq** [syncthing/syncthing-android#1219]
```
$ ./gradlew buildNative

> Configure project :app
Signing not ready. Did you specify a signingConfig for the variation Release?

> Task :syncthing:buildNative FAILED
Building for arm
Building syncthing
# runtime/cgo
In file included from gcc_darwin_amd64.c:6:
In file included from /Users/david/Desktop/syncthing-android/syncthing/gobuild/standalone-ndk/android-16-arm/bin/../sysroot/usr/include/pthread.h:37:
In file included from /Users/david/Desktop/syncthing-android/syncthing/gobuild/standalone-ndk/android-16-arm/bin/../sysroot/usr/include/time.h:33:
In file included from /Users/david/Desktop/syncthing-android/syncthing/gobuild/standalone-ndk/android-16-arm/bin/../sysroot/usr/include/sys/time.h:37:
In file included from /Users/david/Desktop/syncthing-android/syncthing/gobuild/standalone-ndk/android-16-arm/bin/../sysroot/usr/include/sys/select.h:36:
In file included from /Users/david/Desktop/syncthing-android/syncthing/gobuild/standalone-ndk/android-16-arm/bin/../sysroot/usr/include/signal.h:37:
/Users/david/Desktop/syncthing-android/syncthing/gobuild/standalone-ndk/android-16-arm/bin/../sysroot/usr/include/bits/signal_types.h:79:20: error: expected ';' at end of declaration list
/Users/david/Desktop/syncthing-android/syncthing/gobuild/standalone-ndk/android-16-arm/bin/../sysroot/usr/include/bits/signal_types.h:73:18: note: expanded from macro '__SIGACTION_BODY'
/Users/david/Desktop/syncthing-android/syncthing/gobuild/standalone-ndk/android-16-arm/bin/../sysroot/usr/include/asm/signal.h:85:22: note: expanded from macro 'sa_handler'
In file included from gcc_darwin_amd64.c:6:
In file included from /Users/david/Desktop/syncthing-android/syncthing/gobuild/standalone-ndk/android-16-arm/bin/../sysroot/usr/include/pthread.h:37:
In file included from /Users/david/Desktop/syncthing-android/syncthing/gobuild/standalone-ndk/android-16-arm/bin/../sysroot/usr/include/time.h:33:
In file included from /Users/david/Desktop/syncthing-android/syncthing/gobuild/standalone-ndk/android-16-arm/bin/../sysroot/usr/include/sys/time.h:37:
In file included from /Users/david/Desktop/syncthing-android/syncthing/gobuild/standalone-ndk/android-16-arm/bin/../sysroot/usr/include/sys/select.h:36:
In file included from /Users/david/Desktop/syncthing-android/syncthing/gobuild/standalone-ndk/android-16-arm/bin/../sysroot/usr/include/signal.h:37:
/Users/david/Desktop/syncthing-android/syncthing/gobuild/standalone-ndk/android-16-arm/bin/../sysroot/usr/include/bits/signal_types.h:79:20: error: expected ')'
/Users/david/Desktop/syncthing-android/syncthing/gobuild/standalone-ndk/android-16-arm/bin/../sysroot/usr/include/bits/signal_types.h:74:12: note: expanded from macro '__SIGACTION_BODY'
/Users/david/Desktop/syncthing-android/syncthing/gobuild/standalone-ndk/android-16-arm/bin/../sysroot/usr/include/asm/signal.h:86:24: note: expanded from macro 'sa_sigaction'
/Users/david/Desktop/syncthing-android/syncthing/gobuild/standalone-ndk/android-16-arm/bin/../sysroot/usr/include/bits/signal_types.h:79:20: note: to match this '('
/Users/david/Desktop/syncthing-android/syncthing/gobuild/standalone-ndk/android-16-arm/bin/../sysroot/usr/include/bits/signal_types.h:74:10: note: expanded from macro '__SIGACTION_BODY'
/Users/david/Desktop/syncthing-android/syncthing/gobuild/standalone-ndk/android-16-arm/bin/../sysroot/usr/include/bits/signal_types.h:79:20: error: duplicate member '_u'
/Users/david/Desktop/syncthing-android/syncthing/gobuild/standalone-ndk/android-16-arm/bin/../sysroot/usr/include/bits/signal_types.h:74:12: note: expanded from macro '__SIGACTION_BODY'
/Users/david/Desktop/syncthing-android/syncthing/gobuild/standalone-ndk/android-16-arm/bin/../sysroot/usr/include/asm/signal.h:86:22: note: expanded from macro 'sa_sigaction'
/Users/david/Desktop/syncthing-android/syncthing/gobuild/standalone-ndk/android-16-arm/bin/../sysroot/usr/include/bits/signal_types.h:79:20: note: previous declaration is here
/Users/david/Desktop/syncthing-android/syncthing/gobuild/standalone-ndk/android-16-arm/bin/../sysroot/usr/include/bits/signal_types.h:73:18: note: expanded from macro '__SIGACTION_BODY'
/Users/david/Desktop/syncthing-android/syncthing/gobuild/standalone-ndk/android-16-arm/bin/../sysroot/usr/include/asm/signal.h:85:20: note: expanded from macro 'sa_handler'
In file included from gcc_darwin_amd64.c:6:
In file included from /Users/david/Desktop/syncthing-android/syncthing/gobuild/standalone-ndk/android-16-arm/bin/../sysroot/usr/include/pthread.h:37:
In file included from /Users/david/Desktop/syncthing-android/syncthing/gobuild/standalone-ndk/android-16-arm/bin/../sysroot/usr/include/time.h:33:
In file included from /Users/david/Desktop/syncthing-android/syncthing/gobuild/standalone-ndk/android-16-arm/bin/../sysroot/usr/include/sys/time.h:37:
In file included from /Users/david/Desktop/syncthing-android/syncthing/gobuild/standalone-ndk/android-16-arm/bin/../sysroot/usr/include/sys/select.h:36:
In file included from /Users/david/Desktop/syncthing-android/syncthing/gobuild/standalone-ndk/android-16-arm/bin/../sysroot/usr/include/signal.h:37:
/Users/david/Desktop/syncthing-android/syncthing/gobuild/standalone-ndk/android-16-arm/bin/../sysroot/usr/include/bits/signal_types.h:80:22: error: expected ';' at end of declaration list
/Users/david/Desktop/syncthing-android/syncthing/gobuild/standalone-ndk/android-16-arm/bin/../sysroot/usr/include/bits/signal_types.h:73:18: note: expanded from macro '__SIGACTION_BODY'
/Users/david/Desktop/syncthing-android/syncthing/gobuild/standalone-ndk/android-16-arm/bin/../sysroot/usr/include/asm/signal.h:85:22: note: expanded from macro 'sa_handler'
In file included from gcc_darwin_amd64.c:6:
In file included from /Users/david/Desktop/syncthing-android/syncthing/gobuild/standalone-ndk/android-16-arm/bin/../sysroot/usr/include/pthread.h:37:
In file included from /Users/david/Desktop/syncthing-android/syncthing/gobuild/standalone-ndk/android-16-arm/bin/../sysroot/usr/include/time.h:33:
In file included from /Users/david/Desktop/syncthing-android/syncthing/gobuild/standalone-ndk/android-16-arm/bin/../sysroot/usr/include/sys/time.h:37:
In file included from /Users/david/Desktop/syncthing-android/syncthing/gobuild/standalone-ndk/android-16-arm/bin/../sysroot/usr/include/sys/select.h:36:
In file included from /Users/david/Desktop/syncthing-android/syncthing/gobuild/standalone-ndk/android-16-arm/bin/../sysroot/usr/include/signal.h:37:
/Users/david/Desktop/syncthing-android/syncthing/gobuild/standalone-ndk/android-16-arm/bin/../sysroot/usr/include/bits/signal_types.h:80:22: error: expected ')'
/Users/david/Desktop/syncthing-android/syncthing/gobuild/standalone-ndk/android-16-arm/bin/../sysroot/usr/include/bits/signal_types.h:74:12: note: expanded from macro '__SIGACTION_BODY'
/Users/david/Desktop/syncthing-android/syncthing/gobuild/standalone-ndk/android-16-arm/bin/../sysroot/usr/include/asm/signal.h:86:24: note: expanded from macro 'sa_sigaction'
/Users/david/Desktop/syncthing-android/syncthing/gobuild/standalone-ndk/android-16-arm/bin/../sysroot/usr/include/bits/signal_types.h:80:22: note: to match this '('
/Users/david/Desktop/syncthing-android/syncthing/gobuild/standalone-ndk/android-16-arm/bin/../sysroot/usr/include/bits/signal_types.h:74:10: note: expanded from macro '__SIGACTION_BODY'
/Users/david/Desktop/syncthing-android/syncthing/gobuild/standalone-ndk/android-16-arm/bin/../sysroot/usr/include/bits/signal_types.h:80:22: error: duplicate member '_u'
/Users/david/Desktop/syncthing-android/syncthing/gobuild/standalone-ndk/android-16-arm/bin/../sysroot/usr/include/bits/signal_types.h:74:12: note: expanded from macro '__SIGACTION_BODY'
/Users/david/Desktop/syncthing-android/syncthing/gobuild/standalone-ndk/android-16-arm/bin/../sysroot/usr/include/asm/signal.h:86:22: note: expanded from macro 'sa_sigaction'
/Users/david/Desktop/syncthing-android/syncthing/gobuild/standalone-ndk/android-16-arm/bin/../sysroot/usr/include/bits/signal_types.h:80:22: note: previous declaration is here
/Users/david/Desktop/syncthing-android/syncthing/gobuild/standalone-ndk/android-16-arm/bin/../sysroot/usr/include/bits/signal_types.h:73:18: note: expanded from macro '__SIGACTION_BODY'
/Users/david/Desktop/syncthing-android/syncthing/gobuild/standalone-ndk/android-16-arm/bin/../sysroot/usr/include/asm/signal.h:85:20: note: expanded from macro 'sa_handler'
Traceback (most recent call last):
  File "./build-syncthing.py", line 119, in <module>
    ] + pkg_argument + ['-no-upgrade', 'build'], env=environ, cwd=syncthing_dir)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['go', 'run', 'build.go', '-goos', 'android', '-goarch', 'arm', '-pkgdir', '/Users/david/Desktop/syncthing-android/syncthing/gobuild/go-packages/arm', '-no-upgrade', 'build']' returned non-zero exit status 2


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':syncthing:buildNative'.
> Process 'command 'python'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
1 actionable task: 1 executed

```

```
$ go version
go version go1.10.2 darwin/amd64
```

Any tips? Thank you

**Comment by davidhq** [comment]
Great, thank you.. I saw the other issue but for some reason wasn't sure if it's the same problem.

I'll try to wait for Go 1.11 then...

**Comment by AudriusButkevicius** [comment]
Go 1.11 is not likely to work too, unless we fix things.
