### ISSUE TITLE
 Failed to execute syncthing binary or read output

### ISSUE THREAD

**Issue by hahman** [syncthing/syncthing-android#1221]
Failed to execute syncthing binary or read output
                     java.io.IOException: Cannot run program "/data/app/com.nutomic.syncthingandroid.debug-1/lib/arm64/libsyncthing.so": error=2, No such file or directory
                         at java.lang.ProcessBuilder.start(ProcessBuilder.java:983)
                         at com.nutomic.syncthingandroid.service.SyncthingRunnable.setupAndLaunch(SyncthingRunnable.java:464)
                         at com.nutomic.syncthingandroid.service.SyncthingRunnable.run(SyncthingRunnable.java:136)
                         at com.nutomic.syncthingandroid.service.SyncthingRunnable.run(SyncthingRunnable.java:107)
                         at com.nutomic.syncthingandroid.util.ConfigXml.<init>(ConfigXml.java:69)
                         at com.nutomic.syncthingandroid.service.SyncthingService$StartupTask.doInBackground(SyncthingService.java:337)
                         at com.nutomic.syncthingandroid.service.SyncthingService$StartupTask.doInBackground(SyncthingService.java:322)
                         at android.os.AsyncTask$2.call(AsyncTask.java:304)
                         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                         at java.lang.Thread.run(Thread.java:760)
                      Caused by: java.io.IOException: error=2, No such file or directory
                         at java.lang.UNIXProcess.forkAndExec(Native Method)
                         at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
                         at java.lang.ProcessImpl.start(ProcessImpl.java:128)
                         at java.lang.ProcessBuilder.start(ProcessBuilder.java:964)
                         at com.nutomic.syncthingandroid.service.SyncthingRunnable.setupAndLaunch(SyncthingRunnable.java:464) 
                         at com.nutomic.syncthingandroid.service.SyncthingRunnable.run(SyncthingRunnable.java:136) 
                         at com.nutomic.syncthingandroid.service.SyncthingRunnable.run(SyncthingRunnable.java:107) 
                         at com.nutomic.syncthingandroid.util.ConfigXml.<init>(ConfigXml.java:69) 
                         at com.nutomic.syncthingandroid.service.SyncthingService$StartupTask.doInBackground(SyncthingService.java:337) 
                         at com.nutomic.syncthingandroid.service.SyncthingService$StartupTask.doInBackground(SyncthingService.java:322) 
                         at android.os.AsyncTask$2.call(AsyncTask.java:304) 
                         at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                         at java.lang.Thread.run(Thread.java:760) 
E/SyncthingUtil: Root is not available. Cannot fix permissions.

**Comment by hahman** [comment]
I don't know what's going on here. Who can help, thank you！
