### ISSUE TITLE
Configuration inaccessible when running two instances (using android work profile)

### ISSUE THREAD

**Issue by azrdev** [syncthing/syncthing-android#1557]
I'm using the "work profile" feature of Android 9, trying to have two syncthing instances: one for my default "private profile", and another for the work profile.

However, they seem to be both trying to use <127.0.0.1:8384> for their control interfaces, therefore I can configure the one in the app, but when I then open the other app, it stays in the loading screen forever.

logcat loops the following trace:

~~~
10-06 21:10:07.296   649  1257 I ActivityManager: Displayed com.nutomic.syncthingandroid/.activities.MainActivity: +1s803ms
10-06 21:10:07.367  2212  2212 W StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1
10-06 21:10:07.399   307   438 W SurfaceFlinger: Attempting to set client state on removed layer: Splash Screen com.nutomic.syncthingandroid#0
10-06 21:10:07.400   307   438 W SurfaceFlinger: Attempting to destroy on removed layer: Splash Screen com.nutomic.syncthingandroid#0
10-06 21:10:07.402  8776  8776 W PollWebGuiAvailableTask: Unexpected error while polling web gui
10-06 21:10:07.402  8776  8776 W PollWebGuiAvailableTask: com.android.volley.NoConnectionError: javax.net.ssl.SSLHandshakeException: java.lang.RuntimeException: error:1a000064:ECDSA routines:OPENSSL_internal:BAD_SIGNATURE
10-06 21:10:07.402  8776  8776 W PollWebGuiAvailableTask:       at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:181)
10-06 21:10:07.402  8776  8776 W PollWebGuiAvailableTask:       at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
10-06 21:10:07.402  8776  8776 W PollWebGuiAvailableTask:       at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
10-06 21:10:07.402  8776  8776 W PollWebGuiAvailableTask:       at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
10-06 21:10:07.402  8776  8776 W PollWebGuiAvailableTask: Caused by: javax.net.ssl.SSLHandshakeException: java.lang.RuntimeException: error:1a000064:ECDSA routines:OPENSSL_internal:BAD_SIGNATURE
10-06 21:10:07.402  8776  8776 W PollWebGuiAvailableTask:       at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:229)
10-06 21:10:07.402  8776  8776 W PollWebGuiAvailableTask:       at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:192)
10-06 21:10:07.402  8776  8776 W PollWebGuiAvailableTask:       at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
10-06 21:10:07.402  8776  8776 W PollWebGuiAvailableTask:       at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
10-06 21:10:07.402  8776  8776 W PollWebGuiAvailableTask:       at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
10-06 21:10:07.402  8776  8776 W PollWebGuiAvailableTask:       at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
10-06 21:10:07.402  8776  8776 W PollWebGuiAvailableTask:       at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
10-06 21:10:07.402  8776  8776 W PollWebGuiAvailableTask:       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
10-06 21:10:07.402  8776  8776 W PollWebGuiAvailableTask:       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
10-06 21:10:07.402  8776  8776 W PollWebGuiAvailableTask:       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
10-06 21:10:07.402  8776  8776 W PollWebGuiAvailableTask:       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
10-06 21:10:07.402  8776  8776 W PollWebGuiAvailableTask:       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
10-06 21:10:07.402  8776  8776 W PollWebGuiAvailableTask:       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
10-06 21:10:07.402  8776  8776 W PollWebGuiAvailableTask:       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:26)
10-06 21:10:07.402  8776  8776 W PollWebGuiAvailableTask:       at com.android.volley.toolbox.HurlStack.executeRequest(HurlStack.java:96)
10-06 21:10:07.402  8776  8776 W PollWebGuiAvailableTask:       at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:123)
10-06 21:10:07.402  8776  8776 W PollWebGuiAvailableTask:       ... 3 more
10-06 21:10:07.402  8776  8776 W PollWebGuiAvailableTask: Caused by: java.security.cert.CertificateException: java.lang.RuntimeException: error:1a000064:ECDSA routines:OPENSSL_internal:BAD_SIGNATURE
10-06 21:10:07.402  8776  8776 W PollWebGuiAvailableTask:       at com.android.org.conscrypt.OpenSSLX509Certificate.verifyOpenSSL(OpenSSLX509Certificate.java:381)
10-06 21:10:07.402  8776  8776 W PollWebGuiAvailableTask:       at com.android.org.conscrypt.OpenSSLX509Certificate.verify(OpenSSLX509Certificate.java:409)
10-06 21:10:07.402  8776  8776 W PollWebGuiAvailableTask:       at com.nutomic.syncthingandroid.http.SyncthingTrustManager.checkServerTrusted(SyncthingTrustManager.java:54)
10-06 21:10:07.402  8776  8776 W PollWebGuiAvailableTask:       at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:212)
10-06 21:10:07.402  8776  8776 W PollWebGuiAvailableTask:       at com.android.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(ConscryptFileDescriptorSocket.java:404)
10-06 21:10:07.402  8776  8776 W PollWebGuiAvailableTask:       at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
10-06 21:10:07.402  8776  8776 W PollWebGuiAvailableTask:       at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:375)
10-06 21:10:07.402  8776  8776 W PollWebGuiAvailableTask:       at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:224)
10-06 21:10:07.402  8776  8776 W PollWebGuiAvailableTask:       ... 18 more
10-06 21:10:07.402  8776  8776 W PollWebGuiAvailableTask: Caused by: java.lang.RuntimeException: error:1a000064:ECDSA routines:OPENSSL_internal:BAD_SIGNATURE
10-06 21:10:07.402  8776  8776 W PollWebGuiAvailableTask:       at com.android.org.conscrypt.NativeCrypto.X509_verify(Native Method)
10-06 21:10:07.402  8776  8776 W PollWebGuiAvailableTask:       at com.android.org.conscrypt.OpenSSLX509Certificate.verifyOpenSSL(OpenSSLX509Certificate.java:379)
10-06 21:10:07.402  8776  8776 W PollWebGuiAvailableTask:       ... 25 more
~~~

and sometimes after it
~~~
10-06 21:10:07.674  8376  8376 V ApiRequest: Performing request to https://127.0.0.1:8384/rest/events?since=37&limit=0
10-06 21:10:07.681  8376  8376 V EventProcessor: Unhandled event ListenAddressesChanged
10-06 21:10:07.760  8776  8776 V ApiRequest: Performing request to https://127.0.0.1:8384
~~~

### Version Information

    App Version: 1.9.0 from F-Droid
    Syncthing Version: v1.9.0
    Android Version: 9 / LineageOS for MicroG 16.0

**Comment by AudriusButkevicius** [comment]
Sadly it's not a use case that is supported.

**Comment by masgo** [comment]
I am using this setup and it works fine for me. Syncthing v.1.10.0 with Android 9 (LineageOS 16) and a working profile created/manged by Island. 

I can even sync both profiles with the same PC.

**Comment by hiqua** [comment]
It works somewhat fine for me as well, although I don't remember if I configured the ports manually or if the app figured the conflict on its own. @azrdev you can try to set the ports in your work profile manually to something other than 8384.

It's still not so reliable though, and I (can only) suspect that the two instances somehow clash with each other: I recently had this case where my phone had a connection most of the day every day, but the main instance had not connected for 3 days, while the work instance was working correctly.

Overall I feel I regularly have to restart one or the other instance to manually sync files (the two notifications are running, but opening the web interface in one of them results in a 404).

@masgo do you have the same experience, or is it flawless for you?

@AudriusButkevicius I understand that this use-case is not supported, but if you know what could cause bugs / conflicts (other than ports), could you expand? Maybe knowing these would be enough to come up with workarounds.

It could also be that my issues are unrelated to the work profile, and that I would also have them if I only had one instance running, but I don't remember having these before this setup.

**Comment by masgo** [comment]
@hiqua I did some more testing. I have no problems whatsoever on my phone. But I also tried another phone (Xiaomi running stock MIUI 11) and here I had the same issues as described above. So I guess it has something to do with the underlying Android OS. Need to do some more tests with the Xiaomi when I have some spare time.

**Comment by hiqua** [comment]
Ok interesting. In any case I feel that the Android wrapper should detect if the Syncthing instance is dead, and restart it if need be.

**Comment by imsodin** [comment]
Please discuss use-cases and results of experimenting on https://forum.syncthing.net/. If anything actionable turns up during such a discussion, an issue on github can be opened again.

**Comment by azrdev** [comment]
> It works somewhat fine for me as well, although I don't remember if I configured the ports manually or if the app figured the conflict on its own. @azrdev you can try to set the ports in your work profile manually to something other than 8384.

Indeed setting the port of the webinterface of one of the instances to some highport != 8384 just fixed the issue (but reading your comment further, I shall see for how long)

Before, the following traceback was repeated in logcat over and over:

~~~python traceback
01-08 23:19:17.703  6509  6509 V ApiRequest: Performing request to https://127.0.0.1:8384
01-08 23:19:17.922  6509  6509 W PollWebGuiAvailableTask: Unexpected error while polling web gui
01-08 23:19:17.922  6509  6509 W PollWebGuiAvailableTask: com.android.volley.NoConnectionError: javax.net.ssl.SSLHandshakeException: error:1a000064:ECDSA routines:OPENSSL_internal:BAD_SIGNATURE
01-08 23:19:17.922  6509  6509 W PollWebGuiAvailableTask:       at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:181)
01-08 23:19:17.922  6509  6509 W PollWebGuiAvailableTask:       at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
01-08 23:19:17.922  6509  6509 W PollWebGuiAvailableTask:       at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
01-08 23:19:17.922  6509  6509 W PollWebGuiAvailableTask:       at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
01-08 23:19:17.922  6509  6509 W PollWebGuiAvailableTask: Caused by: javax.net.ssl.SSLHandshakeException: error:1a000064:ECDSA routines:OPENSSL_internal:BAD_SIGNATURE
01-08 23:19:17.922  6509  6509 W PollWebGuiAvailableTask:       at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:231)
01-08 23:19:17.922  6509  6509 W PollWebGuiAvailableTask:       at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:196)
01-08 23:19:17.922  6509  6509 W PollWebGuiAvailableTask:       at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
01-08 23:19:17.922  6509  6509 W PollWebGuiAvailableTask:       at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
01-08 23:19:17.922  6509  6509 W PollWebGuiAvailableTask:       at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
01-08 23:19:17.922  6509  6509 W PollWebGuiAvailableTask:       at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
01-08 23:19:17.922  6509  6509 W PollWebGuiAvailableTask:       at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
01-08 23:19:17.922  6509  6509 W PollWebGuiAvailableTask:       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
01-08 23:19:17.922  6509  6509 W PollWebGuiAvailableTask:       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
01-08 23:19:17.922  6509  6509 W PollWebGuiAvailableTask:       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
01-08 23:19:17.922  6509  6509 W PollWebGuiAvailableTask:       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
01-08 23:19:17.922  6509  6509 W PollWebGuiAvailableTask:       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
01-08 23:19:17.922  6509  6509 W PollWebGuiAvailableTask:       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
01-08 23:19:17.922  6509  6509 W PollWebGuiAvailableTask:       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
01-08 23:19:17.922  6509  6509 W PollWebGuiAvailableTask:       at com.android.volley.toolbox.HurlStack.executeRequest(HurlStack.java:96)
01-08 23:19:17.922  6509  6509 W PollWebGuiAvailableTask:       at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:123)
01-08 23:19:17.922  6509  6509 W PollWebGuiAvailableTask:       ... 3 more
01-08 23:19:17.922  6509  6509 W PollWebGuiAvailableTask: Caused by: java.security.cert.CertificateException: error:1a000064:ECDSA routines:OPENSSL_internal:BAD_SIGNATURE
01-08 23:19:17.922  6509  6509 W PollWebGuiAvailableTask:       at com.android.org.conscrypt.NativeCrypto.X509_verify(Native Method)
01-08 23:19:17.922  6509  6509 W PollWebGuiAvailableTask:       at com.android.org.conscrypt.OpenSSLX509Certificate.verifyOpenSSL(OpenSSLX509Certificate.java:381)
01-08 23:19:17.922  6509  6509 W PollWebGuiAvailableTask:       at com.android.org.conscrypt.OpenSSLX509Certificate.verify(OpenSSLX509Certificate.java:411)
01-08 23:19:17.922  6509  6509 W PollWebGuiAvailableTask:       at com.nutomic.syncthingandroid.http.SyncthingTrustManager.checkServerTrusted(SyncthingTrustManager.java:54)
01-08 23:19:17.922  6509  6509 W PollWebGuiAvailableTask:       at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:228)
01-08 23:19:17.922  6509  6509 W PollWebGuiAvailableTask:       at com.android.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(ConscryptFileDescriptorSocket.java:407)
01-08 23:19:17.922  6509  6509 W PollWebGuiAvailableTask:       at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
01-08 23:19:17.922  6509  6509 W PollWebGuiAvailableTask:       at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:387)
01-08 23:19:17.922  6509  6509 W PollWebGuiAvailableTask:       at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:226)
01-08 23:19:17.922  6509  6509 W PollWebGuiAvailableTask:       ... 18 more
~~~
