### ISSUE TITLE
selecting a Folder for File Versioning crashes

### ISSUE THREAD

**Issue by steelbytes** [syncthing/syncthing-android#1912]
trying to select a Folder for File Versioning in the android native ui crashes. 

```
05-27 11:29:49.423 13348 13348 E AndroidRuntime: FATAL EXCEPTION: main
05-27 11:29:49.423 13348 13348 E AndroidRuntime: Process: com.nutomic.syncthingandroid, PID: 13348
05-27 11:29:49.423 13348 13348 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nutomic.syncthingandroid/com.nutomic.syncthingandroid.activities.FolderPickerActivity}: java.lang.NullPointerException: Attempt to get length of null array
05-27 11:29:49.423 13348 13348 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3641)
05-27 11:29:49.423 13348 13348 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3778)
05-27 11:29:49.423 13348 13348 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
05-27 11:29:49.423 13348 13348 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
05-27 11:29:49.423 13348 13348 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
05-27 11:29:49.423 13348 13348 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2303)
05-27 11:29:49.423 13348 13348 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
05-27 11:29:49.423 13348 13348 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
05-27 11:29:49.423 13348 13348 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
05-27 11:29:49.423 13348 13348 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7884)
05-27 11:29:49.423 13348 13348 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
05-27 11:29:49.423 13348 13348 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
05-27 11:29:49.423 13348 13348 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
05-27 11:29:49.423 13348 13348 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to get length of null array
05-27 11:29:49.423 13348 13348 E AndroidRuntime:        at java.util.Collections.addAll(Collections.java:5457)
05-27 11:29:49.423 13348 13348 E AndroidRuntime:        at com.nutomic.syncthingandroid.activities.FolderPickerActivity.populateRoots(FolderPickerActivity.java:142)
05-27 11:29:49.423 13348 13348 E AndroidRuntime:        at com.nutomic.syncthingandroid.activities.FolderPickerActivity.onCreate(FolderPickerActivity.java:98)
05-27 11:29:49.423 13348 13348 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8341)
05-27 11:29:49.423 13348 13348 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8320)
05-27 11:29:49.423 13348 13348 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
05-27 11:29:49.423 13348 13348 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3622)
05-27 11:29:49.423 13348 13348 E AndroidRuntime:        ... 12 more
```

**Comment by imsodin** [comment]
Which app version?

**Comment by steelbytes** [comment]
> Which app version?

1.23.4 (current) from PlayStore

**Comment by steelbytes** [comment]
so .... no fix?

**Comment by er-pa** [comment]
Going after the error message;

`Collections.addAll(roots, new File("/storage/").listFiles());` seems to be the trigger. And I do know that `.listFiles()` can return null if the supplied abstract path is not accessible or a valid directory, which can easily trigger this. And also that accessing `/storage/` is tricky - so the solution may be double-folded.
