### ISSUE TITLE
Installing APK fails with 'java.lang.RuntimeException: Could not copy bitmap to parcel blob'

### ISSUE THREAD

**Issue by raxod502** [syncthing/syncthing-android#2026]
I am unable to install Syncthing on Android 14, receiving the following stack trace from the package installer when attempting to install the APK from https://github.com/syncthing/syncthing-android/releases/tag/1.27.1:

<details>
<summary>Stack trace</summary>

```
type: crash
osVersion: google/bluejay/bluejay:14/UQ1A.231205.015/2023120701:user/release-keys
package: com.android.packageinstaller:34
process: com.android.packageinstaller
processUptime: 1513 + 232 ms

java.lang.RuntimeException: Could not copy bitmap to parcel blob.
at android.graphics.Bitmap.nativeWriteToParcel(Native Method)
at android.graphics.Bitmap.writeToParcel(Bitmap.java:2271)
at android.os.Parcel.writeParcelable(Parcel.java:2586)
at com.android.packageinstaller.PackageUtil$AppSnippet.writeToParcel(PackageUtil.java:151)
at android.os.Parcel.writeParcelable(Parcel.java:2586)
at android.os.Parcel.writeValue(Parcel.java:2487)
at android.os.Parcel.writeValue(Parcel.java:2364)
at android.os.Parcel.writeArrayMapInternal(Parcel.java:1300)
at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1845)
at android.os.Bundle.writeToParcel(Bundle.java:1389)
at android.os.Parcel.writeBundle(Parcel.java:1369)
at android.content.Intent.writeToParcel(Intent.java:11823)
at android.os.Parcel.writeTypedObject(Parcel.java:2205)
at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:2077)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1879)
at android.app.Activity.startActivityForResult(Activity.java:5664)
at com.android.packageinstaller.PackageInstallerActivity.startActivityForResult(PackageInstallerActivity.java:487)
at android.app.Activity.startActivityForResult(Activity.java:5583)
at android.app.Activity.startActivity(Activity.java:6127)
at android.app.Activity.startActivity(Activity.java:6094)
at com.android.packageinstaller.PackageInstallerActivity.startInstall(PackageInstallerActivity.java:744)
at com.android.packageinstaller.PackageInstallerActivity.lambda$bindUi$0(PackageInstallerActivity.java:521)
at com.android.packageinstaller.PackageInstallerActivity.$r8$lambda$RCIm8wl1VPqdfQgkgmrBIDbuvOQ(PackageInstallerActivity.java:0)
at com.android.packageinstaller.PackageInstallerActivity$$ExternalSyntheticLambda0.onClick(R8$$SyntheticClass:0)
at com.android.packageinstaller.AlertController$ButtonHandler.handleMessage(AlertController.java:144)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:205)
at android.os.Looper.loop(Looper.java:294)
at android.app.ActivityThread.main(ActivityThread.java:8216)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ExecInit.main(ExecInit.java:49)
at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
```

</details>

My phone is a Google Pixel 6a running Android 14 (GrapheneOS UQ1A.231205.015.2023120701).

I was previously using https://github.com/Catfriend1/syncthing-android from F-Droid but updates started crashing the installer as of a couple days ago, with the stack trace above. I figured it might be an issue with the fork and so I uninstalled it and tried installing https://github.com/syncthing/syncthing-android instead, however I received the same result. I figured it might an F-Droid problem so I tried installing the APK directly downloaded from this GitHub repository, which had the same result. I tried versions 1.27.1, 1.27.0, 1.26.1, and 1.26.0, which all had the same issue. I am confident that I was previously using one of these versions without a problem, so I think there is an incompatibility with a recent release of GrapheneOS.

Other apps can still be installed and updated on my phone, just not Syncthing (or Syncthing-Fork).

**Comment by bt90** [comment]
To be clear, the Android installer crashes here. This shouldn't happen no matter what we do on our end.

Did you try to contact the GrapheneOS devs?

**Comment by jpacura** [comment]
I'm not sure that this is just GrapheneOS, because I can't get 1.27.0 and 1.27.1 to install from F-Droid on either a Pixel 7 Pro or a Pixel Tablet, both running the latest stock operating system (December 2023). Other F-Droid apps install without problem. I'll check my logs later today to make sure whether it's the same error or not.

**Comment by jpacura** [comment]
Yep, it appears to be the same error message on my Pixel 7 Pro, Stock OS, December 2023 update:

<details>
<summary>Stack Trace</summary>

```java
Process: com.google.android.packageinstaller
java.lang.RuntimeException: Could not copy bitmap to parcel blob.
	at android.graphics.Bitmap.nativeWriteToParcel(Native Method)
	at android.graphics.Bitmap.writeToParcel(Bitmap.java:2271)
	at android.os.Parcel.writeParcelable(Parcel.java:2584)
	at com.android.packageinstaller.PackageUtil$AppSnippet.writeToParcel(PackageUtil.java:151)
	at android.os.Parcel.writeParcelable(Parcel.java:2584)
	at android.os.Parcel.writeValue(Parcel.java:2485)
	at android.os.Parcel.writeValue(Parcel.java:2362)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1298)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1843)
	at android.os.Bundle.writeToParcel(Bundle.java:1389)
	at android.os.Parcel.writeBundle(Parcel.java:1367)
	at android.content.Intent.writeToParcel(Intent.java:11807)
	at android.os.Parcel.writeTypedObject(Parcel.java:2203)
	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:2077)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1873)
	at android.app.Activity.startActivityForResult(Activity.java:5615)
	at android.app.Activity.startActivityForResult(Activity.java:5573)
	at android.app.Activity.startActivity(Activity.java:6071)
	at android.app.Activity.startActivity(Activity.java:6038)
	at com.android.packageinstaller.PackageInstallerActivity.startInstall(PackageInstallerActivity.java:701)
	at com.android.packageinstaller.PackageInstallerActivity.lambda$bindUi$0(PackageInstallerActivity.java:479)
	at com.android.packageinstaller.PackageInstallerActivity.$r8$lambda$RCIm8wl1VPqdfQgkgmrBIDbuvOQ(PackageInstallerActivity.java:0)
	at com.android.packageinstaller.PackageInstallerActivity$$ExternalSyntheticLambda0.onClick(R8$$SyntheticClass:0)
	at com.android.packageinstaller.AlertController$ButtonHandler.handleMessage(AlertController.java:144)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8194)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

</details>

**Comment by jpacura** [comment]
If it helps anything, both of my devices are currently running 1.26.1, installed prior to the December 2023 android update

**Comment by bt90** [comment]
I'm running the fork version v1.27.0.1 installed via F-Droid on my Pixel 4a 5G without problems.

**Comment by raxod502** [comment]
Another app experiencing the same issue has worked around it by resizing an image asset: https://github.com/uazo/cromite/commit/1a8ef384c27b9c9baf8086df71bc2c98c9daf9f7. The workaround has been confirmed to work: https://github.com/uazo/cromite/issues/595#issuecomment-1858179243

I have reported the issue also on the GrapheneOS forum at https://discuss.grapheneos.org/d/9645-javalangruntimeexception-could-not-copy-bitmap-to-parcel-blob as suggested in https://github.com/syncthing/syncthing-android/issues/2026#issuecomment-1858013139.

**Comment by imsodin** [comment]
The reply in the grapheneos thread linked above suggests to me that this is an aosp (android) issue that was fixed, and system updates may not have rolled out to everyone affected:

>  Hello, the fix for this is on the latest version release. Please update your system. 

So I suggest to upgrade your system if you are affected, as soon as you can.

**Comment by jpacura** [comment]
As far as I can tell, the stock pixel rom hasn't released an update yet for this, but it appears to be in the beta changelog, so hopefully they push it in the January update, but that's still almost a month away

**Comment by pbasov** [comment]
Reporting the same issue on Pixel 8 Pro after update to Android 14 UQ1A.231205.015 with the latest F-Droid version.

Really unfortunate, since I've deleted the app too. Google Play version of the app works though, so will continue using that, until the fix is out.

**Comment by jpacura** [comment]
Just in case it helps anyone else that wants to upgrade syncthing before Google fixes this, I was able to download the apk from f-droid (be sure to validate the signature), and install it with `adb install`. It installed on my Pixel 7 Pro without any obvious issues so far, despite still refusing to install from the f-droid app. Because the apk from f-droid's website is identical to the one that the app tries to install, f-droid will still detect it as having been installed from f-droid, and it should not wipe the app's data.

**Comment by cumber** [comment]
> As far as I can tell, the stock pixel rom hasn't released an update yet for this, but it appears to be in the beta changelog, so hopefully they push it in the January update, but that's still almost a month away

I can confirm that I had the issue and was completely unable to install Syncthing, and that when I opted into the Pixel beta and got the newer firmware out was resolved.

So the next firmware update *should* fix it for everyone.

**Comment by FairyTail2000** [comment]
I have the same problem with the fork version of syncthing on the current stable Android Version on my Pixel 6. Forcing an install with adb leads to a success message however an update is not made

**Comment by bt90** [comment]
I've tried to limit the vector path length of our drawables in #2035. Could you test if the app is installable with these changes?

The debug apk can be downloaded for this build: https://github.com/syncthing/syncthing-android/actions/runs/7424933082

**Comment by hcbraun** [comment]
> It may not directly be, but it sure would be nice if the community was able to use this OPEN issue as a focal point until the actual problem is resolved. As it stands, the syncthing-android package (via F-Droid) is the _one and only application out of everything on my devices_ which can't upgrade.

Sadly same thing for me. The last two versions of syncthing via F-Droid do not install for me.

**Comment by bt90** [comment]
If someone is able to figure out what exactly triggers the crash, I could try to patch that.

**Comment by DrStrangeloovee** [comment]
> I've tried to limit the vector path length of our drawables in #2035. Could you test if the app is installable with these changes?
> 
> The debug apk can be downloaded for this build: https://github.com/syncthing/syncthing-android/actions/runs/7424933082
> 
> ![grafik](https://github.com/syncthing/syncthing-android/assets/1926175/1bc169e1-fc59-4059-9c99-7098f2595849)
> 

I had the same initial problem on my Pixel 7a (with 5. Jan. updates) but I was able to install the provided debug apk via `adb install` without any error messages. So far I couldn't find any problems with it.
