### ISSUE TITLE
Service continues to attempt to connect to syncthing after "Exit"

### ISSUE THREAD

**Issue by capi** [syncthing/syncthing-android#258]
Have been trying out self-compiled development version 0.5.21 (7b54ce59b11396782b8c8e1c491a00b419f98f1d), discovered the following issue:

When selecting `Exit`, the native `synthing` process is properly shut down via the REST API, but the Android service seems to be kept running and attempts to connect to the syncthing process, preventing CPU from sleeping and draining battery and filling logcat.
The following goes on until "Force Stop" is selected or device is rebooted (a longer version is available from http://pastebin.com/Ws0paKMq):

    03-19 00:15:49.111  19323-19954/com.nutomic.syncthingandroid.debug I/SyncthingNativeCode? [WMVLO] 23:15:49 INFO: Shutting down
    03-19 00:15:49.111  19323-19954/com.nutomic.syncthingandroid.debug I/SyncthingNativeCode? [WMVLO] 23:15:49 OK: Exiting
    03-19 00:15:49.421  19323-19555/com.nutomic.syncthingandroid.debug W/GetTask? Failed to call Rest API at http://127.0.0.1:8080/rest/model?folder=martin-opo-camera
        org.apache.http.conn.HttpHostConnectException: Connection to http://127.0.0.1:8080 refused
                at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:183)
                at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
                at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
                at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:360)
                at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
                at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
                at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:465)
                at com.nutomic.syncthingandroid.syncthing.GetTask.doInBackground(GetTask.java:63)
                at com.nutomic.syncthingandroid.syncthing.GetTask.doInBackground(GetTask.java:27)
                at android.os.AsyncTask$2.call(AsyncTask.java:288)
                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                at java.lang.Thread.run(Thread.java:841)
         Caused by: java.net.ConnectException: failed to connect to /127.0.0.1 (port 8080): connect failed: ECONNREFUSED (Connection refused)
                at libcore.io.IoBridge.connect(IoBridge.java:114)
                at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:192)
                at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:460)
                at java.net.Socket.connect(Socket.java:833)
                at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:119)
                at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:144)
                at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
                at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
                at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:360)
                at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
                at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
                at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:465)
                at com.nutomic.syncthingandroid.syncthing.GetTask.doInBackground(GetTask.java:63)
                at com.nutomic.syncthingandroid.syncthing.GetTask.doInBackground(GetTask.java:27)
                at android.os.AsyncTask$2.call(AsyncTask.java:288)
                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                at java.lang.Thread.run(Thread.java:841)
         Caused by: libcore.io.ErrnoException: connect failed: ECONNREFUSED (Connection refused)
                at libcore.io.Posix.connect(Native Method)
                at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:85)
                at libcore.io.IoBridge.connectErrno(IoBridge.java:127)
                at libcore.io.IoBridge.connect(IoBridge.java:112)
                at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:192)
                at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:460)
                at java.net.Socket.connect(Socket.java:833)
                at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:119)
                at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:144)
                at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
                at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
                at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:360)
                at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
                at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
                at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:465)
                at com.nutomic.syncthingandroid.syncthing.GetTask.doInBackground(GetTask.java:63)
                at com.nutomic.syncthingandroid.syncthing.GetTask.doInBackground(GetTask.java:27)
                at android.os.AsyncTask$2.call(AsyncTask.java:288)
                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                at java.lang.Thread.run(Thread.java:841)

**Comment by Nutomic** [comment]
The exit button definitely calls [stopService here](https://github.com/syncthing/syncthing-android/blob/master/src/main/java/com/nutomic/syncthingandroid/fragments/DrawerFragment.java#L229).

I think the problem is that Android is caching the service in case it is needed later. In theory it could also be that something is still bound to the service, but the service is only bound in [SyncthingActivity](https://github.com/syncthing/syncthing-android/blob/master/src/main/java/com/nutomic/syncthingandroid/activities/SyncthingActivity.java), and that is properly unbound.

**Comment by capi** [comment]
Well, stopping a service won't kill any background threads it may have created, if it doesn't stop them in the onStop() method. I didn't have time to look at the code to closely yet, maybe I'll have some time to dig in deeper.

**Comment by Zillode** [comment]
@capi I believe it is the GUI trying to connect to the ST service which has been shut down. This can happen with some tasks that were still in the queue, like updating the completion stats. I don't think this is a bad error unless these requests happen endlessly?

**Comment by capi** [comment]
From the stack-trace I cannot see if the tasks are scheduled by the Activity or the Service, and I'm not yet so familiar with the code. I watched it for quite some time in log-cat (several minutes), so I assumed that the tasks were re-scheduling themselves "endlessly", but I'll double-check if they end after some time.

**Comment by Nutomic** [comment]
The RestApi class is started from SyncthingService, and it might still be doing syncthing API calls.

But I don't think there's any actual background threads running, just the service on the GUI thread. But a look over the the code definitely won't hurt ;)

**Comment by capi** [comment]
I was referring to my logcat output in the report. Unfortunately I'm quite busy at the moment and don't have time to investigate right now, hope to find some more time next week.

**Comment by Zillode** [comment]
Further fixes in https://github.com/syncthing/syncthing-android/commit/ad65198f709b8358e5d54e88f1f12c5da4b259fe
