### ISSUE TITLE
java.lang.IllegalStateException: Fragment FoldersFragment is not currently in the FragmentManager

### ISSUE THREAD

**Issue by Zillode** [syncthing/syncthing-android#265]
```
java.lang.IllegalStateException: Fragment FoldersFragment{450eaac0} is not currently in the FragmentManager
at android.support.v4.app.FragmentManagerImpl.putFragment(FragmentManager.java:571)
at com.nutomic.syncthingandroid.activities.MainActivity.onSaveInstanceState(MainActivity.java:227)
at android.app.Activity.performSaveInstanceState(Activity.java:1153)
at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1223)
at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3265)
at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3324)
at android.app.ActivityThread.access$1100(ActivityThread.java:144)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1273)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:212)
at android.app.ActivityThread.main(ActivityThread.java:5137)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:718)
at dalvik.system.NativeStart.main(Native Method)
```

From Play logs

**Comment by Zillode** [comment]
Will be solved with support package 13 from Android, See https://android-review.googlesource.com/#/c/110231/

**Comment by Nutomic** [comment]
It should also be in a new version of support v4 (we can't really use v13 because we still support SDK version 8.

**Comment by Zillode** [comment]
Ref https://github.com/kolavar/android-support-v4-preferencefragment/pull/11

**Comment by Nutomic** [comment]
I don't think this affects us any more.

**Comment by ZhaoKaiQiang** [comment]
https://code.google.com/p/android/issues/detail?id=77285
