### ISSUE TITLE
NPE in org.json.JSONTokener.nextCleanInternal

### ISSUE THREAD

**Issue by Zillode** [syncthing/syncthing-android#270]
```
java.lang.NullPointerException
at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:116)
at org.json.JSONTokener.nextValue(JSONTokener.java:94)
at org.json.JSONObject.<init>(JSONObject.java:155)
at org.json.JSONObject.<init>(JSONObject.java:172)
at com.nutomic.syncthingandroid.syncthing.RestApi$2.onPostExecute(RestApi.java:213)
at com.nutomic.syncthingandroid.syncthing.RestApi$2.onPostExecute(RestApi.java:209)
at android.os.AsyncTask.finish(AsyncTask.java:632)
at android.os.AsyncTask.access$600(AsyncTask.java:177)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5140)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
at dalvik.system.NativeStart.main(Native Method)
```
From Play logs

**Comment by Nutomic** [comment]
Seems to be these lines:
```
JSONObject json = new JSONObject(s);
mVersion = json.getString("version");
```
I assume `s` is null, but that shouldn't really happen (tm). Not sure how to go about it.
