### ISSUE TITLE
JSONException: No value for Invalid

### ISSUE THREAD

**Issue by Zillode** [syncthing/syncthing-android#291]
Not sure?

```
W/RestApi ( 2224): Failed to read devices
W/RestApi ( 2224): org.json.JSONException: No value for Invalid
W/RestApi ( 2224):  at org.json.JSONObject.get(JSONObject.java:389)
W/RestApi ( 2224):  at org.json.JSONObject.getString(JSONObject.java:550)
W/RestApi ( 2224):  at com.nutomic.syncthingandroid.syncthing.RestApi.getFolders(RestApi.java:484)
W/RestApi ( 2224):  at com.nutomic.syncthingandroid.fragments.FoldersFragment.initAdapter(FoldersFragment.java:60)
W/RestApi ( 2224):  at com.nutomic.syncthingandroid.fragments.FoldersFragment.onApiChange(FoldersFragment.java:43)
W/RestApi ( 2224):  at com.nutomic.syncthingandroid.syncthing.SyncthingService.onApiChange(SyncthingService.java:400)
W/RestApi ( 2224):  at com.nutomic.syncthingandroid.syncthing.SyncthingService.access$500(SyncthingService.java:42)
W/RestApi ( 2224):  at com.nutomic.syncthingandroid.syncthing.SyncthingService$PollWebGuiAvailableTaskImpl.onPostExecute(SyncthingService.java:382)
W/RestApi ( 2224):  at com.nutomic.syncthingandroid.syncthing.SyncthingService$PollWebGuiAvailableTaskImpl.onPostExecute(SyncthingService.java:370)
W/RestApi ( 2224):  at android.os.AsyncTask.finish(AsyncTask.java:632)
W/RestApi ( 2224):  at android.os.AsyncTask.access$600(AsyncTask.java:177)
W/RestApi ( 2224):  at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
W/RestApi ( 2224):  at android.os.Handler.dispatchMessage(Handler.java:102)
W/RestApi ( 2224):  at android.os.Looper.loop(Looper.java:135)
W/RestApi ( 2224):  at android.app.ActivityThread.main(ActivityThread.java:5221)
W/RestApi ( 2224):  at java.lang.reflect.Method.invoke(Native Method)
W/RestApi ( 2224):  at java.lang.reflect.Method.invoke(Method.java:372)
W/RestApi ( 2224):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
W/RestApi ( 2224):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
I/RestApi ( 2224): Syncthing version is v0.10.26
```

**Comment by Zillode** [comment]
https://github.com/syncthing/syncthing/blame/v0.10.29/internal/config/config.go#L60
https://github.com/syncthing/syncthing/blame/v0.10.26/internal/config/config.go#L68
https://github.com/syncthing/syncthing/blame/v0.10.20/internal/config/config.go#L67
No apparent change in upstream nor in syncthing-android: https://github.com/syncthing/syncthing-android/blame/master/src/main/java/com/nutomic/syncthingandroid/syncthing/RestApi.java#L484

**Comment by Nutomic** [comment]
The value for the json key "Invalid" is null for some reason. Looks like an upstream problem of some kind.

**Comment by AudriusButkevicius** [comment]
I dont think that it omits empty values, though perhaps the answer was something else than the config, hence it wasn't present at all? But then you wouldn't be able to traverse all the way down to the invalid key.

**Comment by Zillode** [comment]
```
W/GetTask (14068): 	... 19 more
D/AndroidRuntime(14068): Shutting down VM
W/GetTask (14068): Failed to call Rest API at http://127.0.0.1:8080/rest/config
W/GetTask (14068): org.apache.http.conn.HttpHostConnectException: Connection to http://127.0.0.1:8080 refused
W/GetTask (14068): 	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:183)
W/GetTask (14068): 	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
W/GetTask (14068): 	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
W/GetTask (14068): 	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:360)
W/GetTask (14068): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
W/GetTask (14068): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
W/GetTask (14068): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:465)
W/GetTask (14068): 	at com.nutomic.syncthingandroid.syncthing.GetTask.doInBackground(GetTask.java:63)
W/GetTask (14068): 	at com.nutomic.syncthingandroid.syncthing.GetTask.doInBackground(GetTask.java:27)
W/GetTask (14068): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
W/GetTask (14068): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/GetTask (14068): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
W/GetTask (14068): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/GetTask (14068): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/GetTask (14068): 	at java.lang.Thread.run(Thread.java:811)
W/GetTask (14068): Caused by: java.net.ConnectException: failed to connect to /127.0.0.1 (port 8080): connect failed: ECONNREFUSED (Connection refused)
W/GetTask (14068): 	at libcore.io.IoBridge.connect(IoBridge.java:114)
W/GetTask (14068): 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:192)
W/GetTask (14068): 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:460)
W/GetTask (14068): 	at java.net.Socket.connect(Socket.java:833)
W/GetTask (14068): 	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:119)
W/GetTask (14068): 	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:144)
W/GetTask (14068): 	... 14 more
W/GetTask (14068): Caused by: libcore.io.ErrnoException: connect failed: ECONNREFUSED (Connection refused)
W/GetTask (14068): 	at libcore.io.Posix.connect(Native Method)
W/GetTask (14068): 	at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:85)
W/GetTask (14068): 	at libcore.io.IoBridge.connectErrno(IoBridge.java:127)
W/GetTask (14068): 	at libcore.io.IoBridge.connect(IoBridge.java:112)
W/GetTask (14068): 	... 19 more
E/AndroidRuntime(14068): FATAL EXCEPTION: main
E/AndroidRuntime(14068): Process: com.nutomic.syncthingandroid, PID: 14068
E/AndroidRuntime(14068): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
E/AndroidRuntime(14068): 	at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:116)
E/AndroidRuntime(14068): 	at org.json.JSONTokener.nextValue(JSONTokener.java:94)
E/AndroidRuntime(14068): 	at org.json.JSONObject.<init>(JSONObject.java:155)
E/AndroidRuntime(14068): 	at org.json.JSONObject.<init>(JSONObject.java:172)
E/AndroidRuntime(14068): 	at com.nutomic.syncthingandroid.syncthing.RestApi$1.onPostExecute(RestApi.java:208)
E/AndroidRuntime(14068): 	at com.nutomic.syncthingandroid.syncthing.RestApi$1.onPostExecute(RestApi.java:204)
E/AndroidRuntime(14068): 	at android.os.AsyncTask.finish(AsyncTask.java:632)
E/AndroidRuntime(14068): 	at android.os.AsyncTask.access$600(AsyncTask.java:177)
E/AndroidRuntime(14068): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
E/AndroidRuntime(14068): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(14068): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(14068): 	at android.app.ActivityThread.main(ActivityThread.java:5139)
E/AndroidRuntime(14068): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(14068): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
E/AndroidRuntime(14068): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
```

**Comment by Zillode** [comment]
```
java.lang.NullPointerException
at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:116)
at org.json.JSONTokener.nextValue(JSONTokener.java:94)
at org.json.JSONObject.<init>(JSONObject.java:154)
at org.json.JSONObject.<init>(JSONObject.java:171)
at com.nutomic.syncthingandroid.syncthing.RestApi$11.onPostExecute(RestApi.java:880)
at com.nutomic.syncthingandroid.syncthing.RestApi$11.onPostExecute(RestApi.java:873)
at android.os.AsyncTask.finish(AsyncTask.java:631)
at android.os.AsyncTask.access$600(AsyncTask.java:177)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4947)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Zillode** [comment]
This is a very frequent problem based on logs from the play store:/

**Comment by Zillode** [comment]
I tracked all upstream paths but could not see a pattern which would lead to a missing 'invalid' field. Therefore https://github.com/syncthing/syncthing-android/blob/2ed6dac071fbb5757653054724906370e557edfc/src/main/java/com/nutomic/syncthingandroid/syncthing/RestApi.java#L533 should be analyzed further and have a reproducing test.

**Comment by Nutomic** [comment]
It would help to find out under what circumstances this happens. I just tried some things and couldn't reproduce.

Maybe it was fixed upstream in the meantime?

**Comment by Zillode** [comment]
No nothing changed in that regard. If we disable this fix, it will trigger this bug very infrequently.

**Comment by lkwg82** [comment]
Is this still relevant?

**Comment by Zillode** [comment]
It is, with daily crashes on the play store dashboard.

**Comment by lkwg82** [comment]
Do you have an indication if it is specific to a version of android or syncthing or syncthing-android?

**Comment by Zillode** [comment]
![jsonexception](https://cloud.githubusercontent.com/assets/14169/14412317/3ce575d0-ff60-11e5-9d96-69569a2437b5.png)

**Comment by Nutomic** [comment]
Not relevant any more, ecause Gson ignores missing keys.
