### ISSUE TITLE
IllegalArgumentException when dismissing dialog

### ISSUE THREAD

**Issue by Zillode** [syncthing/syncthing-android#297]
From Play logs:
```
java.lang.IllegalArgumentException: View=com.android.internal.policy.impl.PhoneWindow$DecorView{cbb8949 V.E..... R......D 0,0-1368,660} not attached to window manager
at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:386)
at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:312)
at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:84)
at android.app.Dialog.dismissDialog(Dialog.java:341)
at android.app.Dialog.dismiss(Dialog.java:324)
at com.nutomic.syncthingandroid.activities.MainActivity.onApiChange(MainActivity.java:97)
at com.nutomic.syncthingandroid.syncthing.SyncthingService.onApiChange(SyncthingService.java:400)
at com.nutomic.syncthingandroid.syncthing.SyncthingService.access$500(SyncthingService.java:42)
at com.nutomic.syncthingandroid.syncthing.SyncthingService$PollWebGuiAvailableTaskImpl.onPostExecute(SyncthingService.java:382)
at com.nutomic.syncthingandroid.syncthing.SyncthingService$PollWebGuiAvailableTaskImpl.onPostExecute(SyncthingService.java:370)
at android.os.AsyncTask.finish(AsyncTask.java:632)
at android.os.AsyncTask.access$600(AsyncTask.java:177)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5221)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by Nutomic** [comment]
This should be fixed by 2de8d391bf43b8c9c992a2eab08cc41ef963cb52.
