### ISSUE TITLE
StackOverflowError: listFiles in FolderObserver

### ISSUE THREAD

**Issue by Zillode** [syncthing/syncthing-android#326]
From Play logs:
```
java.lang.StackOverflowError
at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:145)
at java.lang.StringBuilder.append(StringBuilder.java:216)
at java.io.File.join(File.java:215)
at java.io.File.<init>(File.java:157)
at java.io.File.<init>(File.java:124)
at com.nutomic.syncthingandroid.util.FolderObserver$1.accept(FolderObserver.java:73)
at java.io.File.list(File.java:773)
at java.io.File.listFiles(File.java:807)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:70)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:79)
at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:32)
at com.nutomic.syncthingandroid.syncthing.SyncthingService$StartupTask$1$1.run(SyncthingService.java:296)
at java.lang.Thread.run(Thread.java:841)
```

**Comment by Zillode** [comment]
(http://stackoverflow.com/questions/16588036/java-lang-stackoverflowerror-recursive-directory)

**Comment by Nutomic** [comment]
The report looks like it only happens to one user, so it would be interesting to see the path for this. Because it seems likely that it's just a bad link.

**Comment by Zillode** [comment]
or a recursive symlink?

**Comment by Nutomic** [comment]
Yeah, and that wouldn't really be our problem. Maybe we could catch the exception, but seems bad if we don't know the actual cause.
