### ISSUE TITLE
NPE in SettingsFragment onApiChange

### ISSUE THREAD

**Issue by Zillode** [syncthing/syncthing-android#328]
```
java.lang.NullPointerException
at com.nutomic.syncthingandroid.fragments.SettingsFragment.onApiChange(SettingsFragment.java:58)
at com.nutomic.syncthingandroid.syncthing.SyncthingService.registerOnApiChangeListener(SyncthingService.java:366)
at com.nutomic.syncthingandroid.fragments.SettingsFragment.onServiceConnected(SettingsFragment.java:151)
at com.nutomic.syncthingandroid.activities.SyncthingActivity.onServiceConnected(SyncthingActivity.java:52)
at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1131)
at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1148)
at android.os.Handler.handleCallback(Handler.java:800)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:194)
at android.app.ActivityThread.main(ActivityThread.java:5371)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Zillode** [comment]
Related
```
java.lang.NullPointerException
at com.nutomic.syncthingandroid.fragments.DeviceSettingsFragment.onReceiveConnections(DeviceSettingsFragment.java:278)
at com.nutomic.syncthingandroid.syncthing.RestApi$8.onPostExecute(RestApi.java:565)
at com.nutomic.syncthingandroid.syncthing.RestApi$8.onPostExecute(RestApi.java:556)
at android.os.AsyncTask.finish(AsyncTask.java:632)
at android.os.AsyncTask.access$600(AsyncTask.java:177)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5146)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Nutomic** [comment]
The second one is probably fixed by the `(mVersion == null || mCurrentAddress == null)` check you added there.

[This](https://github.com/syncthing/syncthing-android/tree/unregister-listener) should help with the first.
