### ISSUE TITLE
My themed icon crashes syncthing

### ISSUE THREAD

**Issue by t184256** [syncthing/syncthing-android#330]
I drew an icon for syncthing that got included into the [TwelF icon theme](https://f-droid.org/repository/browse/?fdfilter=twelf&fdid=org.twelf.cmtheme) since version 0.4. The icon looks nice in the launcher and in the installed application list. The problem is that this icon crashes syncthing when it tries to display the notification (i.e. always on startup after the keys are already created). Here's the logcat:

```
I/Timeline(12791): Timeline: Activity_launch_request id:com.nutomic.syncthingandroid.debug time:16728540
I/ActivityManager(  759): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 pkg=com.nutomic.syncthingandroid.debug cmp=com.nutomic.syncthingandroid.debug/com.nutomic.syncthingandroid.activities.MainActivity} from uid 10083 on display 0
I/ActivityManager(  759): moveTaskToBack: TaskRecord{2fd1dc35 #1073 A=JakedUp.AppDrawer U=0 sz=1}
I/ActivityManager(  759): Start proc com.nutomic.syncthingandroid.debug for activity com.nutomic.syncthingandroid.debug/com.nutomic.syncthingandroid.activities.MainActivity: pid=16688 uid=10082 gids={50082, 9997, 1028, 1015, 3003} abi=armeabi
I/art     (16688): Late-enabling -Xcheck:jni
I/LoadedApk(16688): No resource references to update in package org.twelf.cmtheme
D/OpenGLRenderer(16688): Render dirty regions requested: true
D/Atlas   (16688): Validating map...
I/ConfigXml(16688): Checking for needed config updates
I/Adreno-EGL(16688): <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build: RGURRAM_AU_LINUX_ANDROID_LNX.LA.3.5.2.2_RB1.04.04.04.087.030+PATCH[ES]_msm8974_LNX.LA.3.5.2.2_RB1__release_ENGG ()
I/Adreno-EGL(16688): OpenGL ES Shader Compiler Version: E031.24.00.15
I/Adreno-EGL(16688): Build Date: 08/12/14 Tue
I/Adreno-EGL(16688): Local Branch: 
I/Adreno-EGL(16688): Remote Branch: quic/LNX.LA.3.5.2.2_rb1
I/Adreno-EGL(16688): Local Patches: 8b00bd16f3c1d9d35a2fa902df5e679888d2b2e3 Fixes an llvm crash with mini dEQP apk
I/Adreno-EGL(16688):                  38bad22e162dead4e008444520a0144c78a347bd Fixes a potential dEQP crash.
I/Adreno-EGL(16688):                  ce345e1c45c2ae2d1fb2cb125c8d2574f1af5f95 Rev
I/OpenGLRenderer(16688): Initialized EGL, version 1.4
D/OpenGLRenderer(16688): Enabling debug mode 0
I/SyncthingService(16688): Web GUI will be available at http://127.0.0.1:8080
I/SyncthingService(16688): Starting syncthing according to current state and preferences
I/ConfigXml(16688): Checking for needed config updates
D/WatchIt!( 1308): Connected
E/WatchIt ( 1308): Notification received StatusBarNotification(pkg=com.nutomic.syncthingandroid.debug user=UserHandle{0} id=1 tag=null score=-20 key=0|com.nutomic.syncthingandroid.debug|1|null|10082: Notification(pri=-2 contentView=com.nutomic.syncthingandroid.debug/0x1090078 vibrate=null sound=null defaults=0x0 flags=0x2 color=0x00000000 vis=PRIVATE))
D/WATCHService( 1308): Duplicate message ignored: Syncthing: Syncthing is running
W/ResourceType( 1185): No known package when getting value for resource number 0x62020084
W/StatusBarIconView( 1185): Icon not found in 2130837559: 7f020037
W/StatusBarIconView( 1185): No icon for slot com.nutomic.syncthingandroid.debug/0x1
W/StatusBar( 1185): removeNotification for unknown key: 0|com.nutomic.syncthingandroid.debug|1|null|10082
D/NotificationService(  759): onNotification error pkg=com.nutomic.syncthingandroid.debug tag=null id=1; will crashApplication(uid=10082, pid=16688)
D/****WatchIt***( 1308): No big notif
E/WatchIt!( 1308): Notification received StatusBarNotification(pkg=com.nutomic.syncthingandroid.debug user=UserHandle{0} id=1 tag=null score=-20 key=0|com.nutomic.syncthingandroid.debug|1|null|10082: Notification(pri=-2 contentView=null vibrate=null sound=null defaults=0x0 flags=0x2 color=0x00000000 vis=PRIVATE))
W/StatusBar( 1185): removeNotification for unknown key: 0|com.nutomic.syncthingandroid.debug|1|null|10082
I/HK/LatinKeyboardBaseView( 1346): closing org.pocketworkstation.pckeyboard.LatinKeyboardView{26538d3b V.ED.... ......ID 0,0-1080,436 #7f07000a app:id/LatinkeyboardBaseView}
D/AndroidRuntime(16688): Shutting down VM
E/AndroidRuntime(16688): FATAL EXCEPTION: main
E/AndroidRuntime(16688): Process: com.nutomic.syncthingandroid.debug, PID: 16688
E/AndroidRuntime(16688): android.app.RemoteServiceException: Bad notification posted from package com.nutomic.syncthingandroid.debug: Couldn't create icon: StatusBarIcon(pkg=com.nutomic.syncthingandroid.debuguser=0 id=0x7f020037 level=0 visible=true num=0 )
E/AndroidRuntime(16688): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1459)
E/AndroidRuntime(16688): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(16688): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(16688): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime(16688): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16688): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(16688): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
E/AndroidRuntime(16688): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
W/ActivityManager(  759):   Force finishing activity com.nutomic.syncthingandroid.debug/com.nutomic.syncthingandroid.activities.MainActivity
I/OpenGLRenderer(  759): Initialized EGL, version 1.4
W/ActivityManager(  759): Activity pause timeout for ActivityRecord{22d83d7d u0 com.nutomic.syncthingandroid.debug/com.nutomic.syncthingandroid.activities.MainActivity t1086 f}
W/bs_taimport(16751): Failed to read unit 2561: Unit not found
W/bs_taimport(16751): Failed to read unit 2562: Unit not found
W/bs_taimport(16751): Failed to read unit 2563: Unit not found
I/Timeline(15265): Timeline: Activity_idle id: android.os.BinderProxy@345372a4 time:16729927
I/Timeline(  759): Timeline: Activity_windows_visible id: ActivityRecord{3dcc4eb u0 org.adw.launcher/.Launcher t1082} time:16730069
I/Timeline(  759): Timeline: Activity_windows_visible id: ActivityRecord{22d83d7d u0 com.nutomic.syncthingandroid.debug/com.nutomic.syncthingandroid.activities.MainActivity t1086 f} time:16730169
I/SyncthingRunnable-Nice(16688): ionice performed on libsyncthing.so
I/art     (  759): Explicit concurrent mark sweep GC freed 65720(4MB) AllocSpace objects, 16(4MB) LOS objects, 33% free, 23MB/35MB, paused 1.282ms total 78.742ms
I/SyncthingNativeCode(16688): [HL7FM] 08:25:33 INFO: syncthing v0.10.29 (go1.4 linux-arm android) unknown-user@cola 2015-03-22 14:09:14 UTC
```

I don't think that I did something awful while theming the icon, so I would like to ask you what could be the problem. Can you help me? Is it a problem with the theme or with syncthing itself?

**Comment by Nutomic** [comment]
I have no idea about theming at all, and that log doesn't hepl either. Maybe the theme's creator can help you?

**Comment by Zillode** [comment]
Isn't this solved by restarting the app?

**Comment by t184256** [comment]
No, it's 100% repeatable, as if syncthing-android supports only a specific icon in its notification and the android wrapper forcecloses with other icons.
