### ISSUE TITLE
Exit -> Immediate restart -> API hangs sometimes

### ISSUE THREAD

**Issue by Profpatsch** [syncthing/syncthing-android#356]
When exiting and immediately restarting the app (as you do for a manual restart after ignoring the prompt) sometimes “Waiting for API” hangs indefinitely.

**Comment by Nutomic** [comment]
Can you post a logcat please?

**Comment by Profpatsch** [comment]
Ah, got it:

When I hit `Exit`, it starts throwing these errors:

```
W/GetTask (15259): Retrying GetTask Rest API call (6)
W/GetTask (15259): Failed to call Rest API at http://127.0.0.1:8080/rest/connections
W/GetTask (15259): org.apache.http.conn.HttpHostConnectException: Connection to http://127.0.0.1:8080 refused
W/GetTask (15259): 	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:183)
W/GetTask (15259): 	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
W/GetTask (15259): 	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
W/GetTask (15259): 	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:360)
W/GetTask (15259): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
W/GetTask (15259): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
W/GetTask (15259): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:465)
W/GetTask (15259): 	at com.nutomic.syncthingandroid.syncthing.b.a(Unknown Source)
W/GetTask (15259): 	at com.nutomic.syncthingandroid.syncthing.b.doInBackground(Unknown Source)
W/GetTask (15259): 	at android.os.AsyncTask$2.call(AsyncTask.java:287)
W/GetTask (15259): 	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
W/GetTask (15259): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
W/GetTask (15259): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
W/GetTask (15259): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
W/GetTask (15259): 	at java.lang.Thread.run(Thread.java:856)
W/GetTask (15259): Caused by: java.net.ConnectException: failed to connect to /127.0.0.1 (port 8080): connect failed: ECONNREFUSED (Connection refused)
W/GetTask (15259): 	at libcore.io.IoBridge.connect(IoBridge.java:114)
W/GetTask (15259): 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:192)
W/GetTask (15259): 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:459)
W/GetTask (15259): 	at java.net.Socket.connect(Socket.java:842)
W/GetTask (15259): 	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:119)
W/GetTask (15259): 	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:144)
W/GetTask (15259): 	... 14 more
W/GetTask (15259): Caused by: libcore.io.ErrnoException: connect failed: ECONNREFUSED (Connection refused)
W/GetTask (15259): 	at libcore.io.Posix.connect(Native Method)
W/GetTask (15259): 	at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:85)
W/GetTask (15259): 	at libcore.io.IoBridge.connectErrno(IoBridge.java:127)
W/GetTask (15259): 	at libcore.io.IoBridge.connect(IoBridge.java:112)
W/GetTask (15259): 	... 19 more
```

every few seconds and retries about 20 times (>1min).
Then it stops and starts the background process. All the time “Waiting for API” is displayed.

**Comment by Zillode** [comment]
I think this is resolved. @Profpatsch could you try https://forum.syncthing.net/t/is-syncthing-android-for-0-11-available-for-testing/2443/3 ?

**Comment by Profpatsch** [comment]
Yep, it terminates cleanly now.
