### ISSUE TITLE
App Cracches when try to use QR Code option

### ISSUE THREAD

**Issue by marmundo** [syncthing/syncthing-android#372]
In my Android 5.0.1 running in Nexus 5, the app crashes when try to use the QR code option in add device

**Comment by Nutomic** [comment]
Can you post a [logcat](https://github.com/syncthing/syncthing-android/blob/master/CONTRIBUTING.md#bug-reports) please?

**Comment by trizzone52** [comment]
Google play version doesn't appear to have Camera permissions. Only has Photo/Media/Files.
```
04-26 10:49:07.105 I/ActivityManager(723): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.nutomic.syncthingandroid/.activities.MainActivity} from uid 10051 on display 0
04-26 10:49:08.536 I/ActivityManager(723): START u0 {act=device_settings_fragment cmp=com.nutomic.syncthingandroid/.activities.SettingsActivity (has extras)} from uid 10257 on display 0
04-26 10:49:08.847 I/ActivityManager(723): Displayed com.nutomic.syncthingandroid/.activities.SettingsActivity: +292ms
04-26 10:49:10.058 W/ActivityManager(723): Permission Denial: starting Intent { act=com.google.zxing.client.android.SCAN cat=[android.intent.category.DEFAULT] flg=0x4080000 cmp=com.ups.mobile.android/com.google.zxing.client.android.CaptureActivity } from ProcessRecord{1fe69682 11699:com.nutomic.syncthingandroid/u0a257} (pid=11699, uid=10257) not exported from uid 10234
04-26 10:49:10.058 E/AndroidRuntime(11699): Process: com.nutomic.syncthingandroid, PID: 11699
04-26 10:49:10.058 E/AndroidRuntime(11699): Caused by: java.lang.SecurityException: Permission Denial: starting Intent { act=com.google.zxing.client.android.SCAN cat=[android.intent.category.DEFAULT] flg=0x4080000 cmp=com.ups.mobile.android/com.google.zxing.client.android.CaptureActivity } from ProcessRecord{1fe69682 11699:com.nutomic.syncthingandroid/u0a257} (pid=11699, uid=10257) not exported from uid 10234
04-26 10:49:10.058 E/AndroidRuntime(11699): 	at com.nutomic.syncthingandroid.a.a.onClick(Unknown Source)
04-26 10:49:10.058 E/AndroidRuntime(11699): 	at com.nutomic.syncthingandroid.activities.SettingsActivity.onClick(Unknown Source)
04-26 10:49:10.058 E/ActivityManager(723): App crashed! Process: com.nutomic.syncthingandroid
04-26 10:49:10.068 W/ActivityManager(723):   Force finishing activity com.nutomic.syncthingandroid/.activities.SettingsActivity
04-26 10:49:10.568 W/ActivityManager(723): Activity pause timeout for ActivityRecord{18d45747 u0 com.nutomic.syncthingandroid/.activities.SettingsActivity t600 f}
04-26 10:49:11.690 I/WindowState(723): WIN DEATH: Window{75c5471 u0 com.nutomic.syncthingandroid/com.nutomic.syncthingandroid.activities.MainActivity}
04-26 10:49:11.690 I/WindowState(723): WIN DEATH: Window{21d21c5e u0 com.nutomic.syncthingandroid/com.nutomic.syncthingandroid.activities.SettingsActivity}
04-26 10:49:11.900 I/ActivityManager(723): Process com.nutomic.syncthingandroid (pid 11699) has died
04-26 10:49:11.900 W/ActivityManager(723): Scheduling restart of crashed service com.nutomic.syncthingandroid/.syncthing.SyncthingService in 1000ms
04-26 10:49:11.920 I/AnimationUtil(723): isHTCRecent(Syncthing/Recent screens.)/1
```

**Comment by marmundo** [comment]
This problem happen when I used in my phone. I submitted the error using
google bug report. How can I use logcat in my phone?


Marcelo Damasceno
Lecturer at IFRN/São Gonçalo do Amarante
+55 84 9947-6324
http://about.me/marcelodamasceno


Man can acquire knowledge or becomes an animal, as he will. God makes the
animals, man makes himself.
Georg Lichetnbery
--

**Comment by Zillode** [comment]
Merged, fixed in next release
