### ISSUE TITLE
Log window crashes

### ISSUE THREAD

**Issue by Zillode** [syncthing/syncthing-android#389]
```
java.lang.NullPointerException
at com.nutomic.syncthingandroid.activities.LogActivity.onCreateOptionsMenu(Unknown Source)
at android.app.Activity.onCreatePanelMenu(Activity.java:2158)
at android.support.v4.app.o.onCreatePanelMenu(Unknown Source)
at android.support.v7.app.f.a(Unknown Source)
at android.support.v7.app.h.a(Unknown Source)
at android.support.v7.app.ActionBarActivityDelegateBase.b(Unknown Source)
at android.support.v7.app.ActionBarActivityDelegateBase.d(Unknown Source)
at android.support.v7.app.ActionBarActivityDelegateBase.a(Unknown Source)
at android.support.v7.app.j.run(Unknown Source)
at android.os.Handler.handleCallback(Handler.java:587)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:130)
at android.app.ActivityThread.main(ActivityThread.java:3687)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
at dalvik.system.NativeStart.main(Native Method)
```

I can reproduce this with a release build (f-droid) but not for debug builds, any idea @Nutomic ?

**Comment by Nutomic** [comment]
That's the log I get right before the NPE:
```
W/SupportMenuInflater(15841): Cannot instantiate class: android.support.v7.widget.ShareActionProvider
W/SupportMenuInflater(15841): java.lang.ClassNotFoundException: Didn't find class "android.support.v7.widget.ShareActionProvider" on path: DexPathList[[zip file "/data/app/com.nutomic.syncthingandroid-2/base.apk"],nativeLibraryDirectories=[/data/app/com.nutomic.syncthingandroid-2/lib/arm, /vendor/lib, /system/lib]]
W/SupportMenuInflater(15841):   at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
W/SupportMenuInflater(15841):   at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
W/SupportMenuInflater(15841):   at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
W/SupportMenuInflater(15841):   at android.support.v7.internal.view.g.a(Unknown Source)
W/SupportMenuInflater(15841):   at android.support.v7.internal.view.g.b(Unknown Source)
W/SupportMenuInflater(15841):   at android.support.v7.internal.view.e.a(Unknown Source)
W/SupportMenuInflater(15841):   at android.support.v7.internal.view.e.inflate(Unknown Source)
W/SupportMenuInflater(15841):   at com.nutomic.syncthingandroid.activities.LogActivity.onCreateOptionsMenu(Unknown Source)
W/SupportMenuInflater(15841):   at android.app.Activity.onCreatePanelMenu(Activity.java:2823)
W/SupportMenuInflater(15841):   at android.support.v4.app.o.onCreatePanelMenu(Unknown Source)
W/SupportMenuInflater(15841):   at android.support.v7.app.f.a(Unknown Source)
W/SupportMenuInflater(15841):   at android.support.v7.app.h.a(Unknown Source)
W/SupportMenuInflater(15841):   at android.support.v7.app.ActionBarActivityDelegateBase.b(Unknown Source)
W/SupportMenuInflater(15841):   at android.support.v7.app.ActionBarActivityDelegateBase.d(Unknown Source)
W/SupportMenuInflater(15841):   at android.support.v7.app.ActionBarActivityDelegateBase.a(Unknown Source)
W/SupportMenuInflater(15841):   at android.support.v7.app.j.run(Unknown Source)
W/SupportMenuInflater(15841):   at android.os.Handler.handleCallback(Handler.java:739)
W/SupportMenuInflater(15841):   at android.os.Handler.dispatchMessage(Handler.java:95)
W/SupportMenuInflater(15841):   at android.os.Looper.loop(Looper.java:135)
W/SupportMenuInflater(15841):   at android.app.ActivityThread.main(ActivityThread.java:5254)
W/SupportMenuInflater(15841):   at java.lang.reflect.Method.invoke(Native Method)
W/SupportMenuInflater(15841):   at java.lang.reflect.Method.invoke(Method.java:372)
W/SupportMenuInflater(15841):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
W/SupportMenuInflater(15841):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
W/SupportMenuInflater(15841):   Suppressed: java.lang.ClassNotFoundException: android.support.v7.widget.ShareActionProvider
W/SupportMenuInflater(15841):           at java.lang.Class.classForName(Native Method)
W/SupportMenuInflater(15841):           at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
W/SupportMenuInflater(15841):           at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
W/SupportMenuInflater(15841):           at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
W/SupportMenuInflater(15841):           ... 22 more
W/SupportMenuInflater(15841):   Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```
So it's missing that dependency for some reason.

**Comment by Zillode** [comment]
I've tried some proguard things but it keeps crashing when compiling using `release`
