### ISSUE TITLE
Support for older devices

### ISSUE THREAD

**Issue by nzamotaev** [syncthing/syncthing-android#43]
I am trying to run syncthing on an Acer Liquid E with CyanogenMod 7.
It crashes after showing the "first start" window, even without me pressing the button.

Logcat shows this:

```
E/AndroidRuntime( 3857): FATAL EXCEPTION: Thread-13
E/AndroidRuntime( 3857): com.nutomic.syncthingandroid.syncthing.SyncthingService$NativeExecutionException: Syncthing binary returned error code 1
E/AndroidRuntime( 3857):
E/AndroidRuntime( 3857): runtime: this CPU has no VFPv3 floating point hardware, so it cannot run
E/AndroidRuntime( 3857): this GOARM=7 binary. Recompile using GOARM=6.
E/AndroidRuntime( 3857):
E/AndroidRuntime( 3857):
E/AndroidRuntime( 3857):        at com.nutomic.syncthingandroid.syncthing.SyncthingService.runNative(SyncthingService.java:163)
E/AndroidRuntime( 3857):        at com.nutomic.syncthingandroid.syncthing.SyncthingService.access$1000(SyncthingService.java:53)
E/AndroidRuntime( 3857):        at com.nutomic.syncthingandroid.syncthing.SyncthingService$3.run(SyncthingService.java:332)
E/AndroidRuntime( 3857):        at java.lang.Thread.run(Thread.java:1019)
```

Is it possible to have a build for older devices, or am I on my own in building syncthing?

**Comment by Modiug** [comment]
Just wanted to add that this issue is solved, as Go only uses a single generic "armeabi" by now.
