### ISSUE TITLE
Syncthing binary crashed with error code 1

### ISSUE THREAD

**Issue by Links2004** [syncthing/syncthing-android#464]
I try to use syncthing for android (0.6.6) from store.
but since my device is crashed one it stop working.
i try to reinstall it but all has the same effect loading for ever. 

![image](https://cloud.githubusercontent.com/assets/974709/10315778/88407364-6c5c-11e5-8a5d-3ee93edfdcf6.png)

the log says Syncthing binary crashed with error code 1

log:
```log
10-06 18:58:47.577: I/Timeline(12724): Timeline: Activity_launch_request id:com.nutomic.syncthingandroid time:229547188
10-06 18:58:47.578: I/ActivityManager(20405): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.nutomic.syncthingandroid/.activities.MainActivity} from uid 10223 on display 0
10-06 18:58:47.582: V/WindowManager(20405): addAppToken: AppWindowToken{103fac5a token=Token{11d74405 ActivityRecord{2f73137c u0 com.nutomic.syncthingandroid/.activities.MainActivity t1558}}} to stack=1 task=1558 at 0
10-06 18:58:47.595: V/WindowManager(20405): Based on layer: Adding window Window{216eeebd u0 Starting com.nutomic.syncthingandroid} at 8 of 14
10-06 18:58:47.621: I/ActivityManager(20405): Start proc 3395:com.nutomic.syncthingandroid/u0a249 for activity com.nutomic.syncthingandroid/.activities.MainActivity
10-06 18:58:47.896: V/WindowManager(20405): Adding window Window{390ff2d6 u0 com.nutomic.syncthingandroid/com.nutomic.syncthingandroid.activities.MainActivity} at 8 of 15 (before Window{216eeebd u0 Starting com.nutomic.syncthingandroid})
10-06 18:58:48.101: V/WindowManager(20405): Adding window Window{d59a3f3 u0 com.nutomic.syncthingandroid/com.nutomic.syncthingandroid.activities.MainActivity} at 9 of 16 (before Window{216eeebd u0 Starting com.nutomic.syncthingandroid})
10-06 18:58:48.121: I/SyncthingService(3395): Starting syncthing according to current state and preferences
10-06 18:58:48.157: I/chmod(3425): type=1400 audit(0.0:39987): avc: denied { setattr } for name="libsyncthing.so" dev="mmcblk0p30" ino=899383 scontext=u:r:untrusted_app:s0 tcontext=u:object_r:apk_data_file:s0 tclass=file permissive=1
10-06 18:58:48.241: I/SyncthingNativeCode(3395): 16:58:48 WARNING: chmod /data/data/com.nutomic.syncthingandroid/files: operation not permitted
10-06 18:58:48.316: I/ActivityManager(20405): Displayed com.nutomic.syncthingandroid/.activities.MainActivity: +721ms
10-06 18:58:48.523: I/Timeline(20405): Timeline: Activity_windows_visible id: ActivityRecord{2f73137c u0 com.nutomic.syncthingandroid/.activities.MainActivity t1558} time:229548134
10-06 18:58:49.274: I/SyncthingRunnableIoNice(3395): ionice performed on libsyncthing.so
10-06 18:58:53.779: I/SyncthingNativeCode(3395): [MNITJ] 16:58:53 INFO: syncthing v0.11.22 "Aluminium Ant" (go1.4.2 linux-arm android) unknown-user@android.syncthing.net 2015-08-24 07:40:21 UTC
10-06 18:58:59.352: E/SyncthingNativeCode(3395): Syncthing binary crashed with error code 1
```

**Comment by Nutomic** [comment]
What's device and Android version are you using?

cc @calmh @AudriusButkevicius

**Comment by AudriusButkevicius** [comment]
No clue honestly. You'd have to compile a special version with verbose logging to figure out where it's happening.

**Comment by Links2004** [comment]
it´s an Nexus 7 LTE with CM12.1
can I download this special version some where?
I don´t have the build environment to compile it.

**Comment by AudriusButkevicius** [comment]
There is no special version. Best I can suggest is setting the debug setting in the app to `all` and see if that print more logs.

There is no special version with more verbose logging which would allow us to identify where it crashes, and producing one would be a fair amount of work given we don't have access to the device, as we'd have to add logging, produce the build, you'd run the build, we'd see roughly where it crashes, produce another build with more logging, etc, until we know where it crashes.

I know there are some variables such as GODEBUG and GOTRACEBACK, which when set could potentially produce more output and provide a core dump, but you'd again have to compile a special version of the just to be able to set these.

**Comment by Nutomic** [comment]
I just wrote up instructions how to run Syncthing directly (as you probably can't access the app settings):
https://github.com/syncthing/syncthing-android/blob/master/CONTRIBUTING.md#running-syncthing-directly

**Comment by Links2004** [comment]
```./libsyncthing.so -home /data/data/com.nutomic.syncthingandroid/files/```

gives me this:
```
[monitor] 19:50:57 INFO: Starting syncthing
[MNITJ] 19:51:02 INFO: syncthing v0.11.22 "Aluminium Ant" (go1.4.2 linux-arm android) unknown-user@android.syncthing.net 2015-08-24 07:40:21 UTC
[MNITJ] 19:51:02 INFO: My ID: aaaa-ddAAAA-BBBB-AAAA-YYYY-XXXX
[MNITJ] 19:51:02 INFO: Database block cache capacity 14360 KiB
[MNITJ] 19:51:02 OK: Ready to synchronize mobil (read-write)
[MNITJ] 19:51:02 OK: Ready to synchronize images (read-write)
[MNITJ] 19:51:02 INFO: Starting web GUI on https://127.0.0.1:8384/
[MNITJ] 19:51:02 INFO: Completed initial scan (rw) of folder mobil
[MNITJ] 19:51:02 INFO: Completed initial scan (rw) of folder images
[MNITJ] 19:51:06 FATAL: Cannot start GUI: listen tcp 127.0.0.1:8384: bind: address already in use
[monitor] 19:51:06 INFO: Syncthing exited: exit status 1
```

when i check the port 8384 with
```netstat -lpna | grep 8384```
i get many CLOSE_WAIT
```
tcp      518      0 127.0.0.1:8384          127.0.0.1:39900         CLOSE_WAIT -
tcp      518      0 127.0.0.1:8384          127.0.0.1:40014         CLOSE_WAIT -
tcp      518      0 127.0.0.1:8384          127.0.0.1:40097         CLOSE_WAIT -
tcp      518      0 127.0.0.1:8384          127.0.0.1:39984         CLOSE_WAIT -
tcp      518      0 127.0.0.1:8384          127.0.0.1:40032         CLOSE_WAIT -
tcp      518      0 127.0.0.1:8384          127.0.0.1:40109         CLOSE_WAIT -
tcp      518      0 127.0.0.1:8384          127.0.0.1:39951         CLOSE_WAIT -
tcp      518      0 127.0.0.1:8384          127.0.0.1:40110         CLOSE_WAIT -
tcp      518      0 127.0.0.1:8384          127.0.0.1:39909         CLOSE_WAIT -
tcp      518      0 127.0.0.1:8384          127.0.0.1:39908         CLOSE_WAIT -
tcp      518      0 127.0.0.1:8384          127.0.0.1:40018         CLOSE_WAIT -
tcp       32      0 ::ffff:127.0.0.1:57593  ::ffff:127.0.0.1:8384   CLOSE_WAIT -
tcp       32      0 ::ffff:127.0.0.1:58648  ::ffff:127.0.0.1:8384   CLOSE_WAIT -
tcp       32      0 ::ffff:127.0.0.1:60288  ::ffff:127.0.0.1:8384   CLOSE_WAIT -
tcp       32      0 ::ffff:127.0.0.1:60400  ::ffff:127.0.0.1:8384   CLOSE_WAIT -
```

```ps | grep libsyncthing.so```
shows two running processes
```
u0_a246   2485  32052 0      0     c016fa6c 00000000 Z libsyncthing.so
u0_a246   23119 1     0      0     ffffffff 00000000 Z libsyncthing.so
```
but i cant kill them
```kill -9``` and ```killall``` is not working on them.

the APP is closed and killed with long pressing the back button to be sure.

if i change all ports in config.xml i can start syncthing with root.

may there is a problem with the closing libsyncthing one time which then blocks the ports forever.
will try to find some more tomorrow.

**Comment by Nutomic** [comment]
Can you restart your device, *not* start the Syncthing app and then try the command line again?

**Comment by Links2004** [comment]
after a restart I can run it as root with adb.
I only had to change the paths because the root user dont see the file system in the same way then the sandbox from the APP.

when I then start the APP it trys to load libsyncthing.so again?
is there no check if the syncthing already running?
may simply checking the ```ps | grep libsyncthing.so``` output or trying to connect to the 8384 port?

```
10-08 17:31:31.202: W/SyncthingService(21702): com.nutomic.syncthingandroid.util.FolderObserver$FolderNotExistingException: path /mnt/shell/emulated/0/syncthing/mobil does not exist, aborting file observer
10-08 17:31:31.202: W/SyncthingService(21702): 	at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:68)
10-08 17:31:31.202: W/SyncthingService(21702): 	at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:32)
10-08 17:31:31.202: W/SyncthingService(21702): 	at com.nutomic.syncthingandroid.syncthing.SyncthingService$StartupTask$1$1.run(SyncthingService.java:351)
10-08 17:31:31.203: W/SyncthingService(21702): com.nutomic.syncthingandroid.util.FolderObserver$FolderNotExistingException: path /mnt/shell/emulated/0/DCIM does not exist, aborting file observer
10-08 17:31:31.203: W/SyncthingService(21702): 	at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:68)
10-08 17:31:31.203: W/SyncthingService(21702): 	at com.nutomic.syncthingandroid.util.FolderObserver.<init>(FolderObserver.java:32)
10-08 17:31:31.203: W/SyncthingService(21702): 	at com.nutomic.syncthingandroid.syncthing.SyncthingService$StartupTask$1$1.run(SyncthingService.java:351)
10-08 17:31:31.687: I/SyncthingRunnableIoNice(21702): ionice performed on libsyncthing.so
10-08 17:31:35.514: I/SyncthingNativeCode(21702): [GPXTC] 15:31:35 INFO: syncthing v0.11.22 "Aluminium Ant" (go1.4.2 linux-arm android) unknown-user@android.syncthing.net 2015-08-24 07:40:21 UTC
10-08 17:31:35.525: I/SyncthingNativeCode(21702): [GPXTC] 15:31:35 FATAL: Cannot open database: resource temporarily unavailable - Is another copy of Syncthing already running?
10-08 17:31:35.530: E/SyncthingNativeCode(21702): Syncthing binary crashed with error code 1
```
 
the interesting the app then runs but it have problems with the paths (see log).

**Comment by Links2004** [comment]
k one big problem with this workaround. 
I can not use syncthing only in WLAN, it take a some data form my free data today...

**Comment by Nutomic** [comment]
If you're still having this problem, please open an issue at syncthing.
