### ISSUE TITLE
Beta issues

### ISSUE THREAD

**Issue by AudriusButkevicius** [syncthing/syncthing-android#470]
Ann servers shows 0/0 though web ui shows 5/8 (with only 6 beind defined?)
Logs for android and syncthing are missing (needs root?)
Opening web ui, going back and opening settings crashes the app

**Comment by Nutomic** [comment]
The number of announce servers seems to be a Syncthing issue. I tried a clean install on Ubuntu, and got the same numbers.

I can't reproduce the crash, can you post a logcat?

**Comment by AudriusButkevicius** [comment]
```
D/AndroidRuntime( 7863): Shutting down VM
E/AndroidRuntime( 7863): FATAL EXCEPTION: main
E/AndroidRuntime( 7863): Process: com.nutomic.syncthingandroid, PID: 7863
E/AndroidRuntime( 7863): java.lang.RuntimeException: Invalid usage report value
E/AndroidRuntime( 7863):        at com.nutomic.syncthingandroid.syncthing.RestApi.getUsageReportAccepted(RestApi.java:986)
E/AndroidRuntime( 7863):        at com.nutomic.syncthingandroid.fragments.SettingsFragment.onApiChange(SettingsFragment.java:79)
E/AndroidRuntime( 7863):        at com.nutomic.syncthingandroid.syncthing.SyncthingService.registerOnApiChangeListener(SyncthingService.java:443)
E/AndroidRuntime( 7863):        at com.nutomic.syncthingandroid.fragments.SettingsFragment.onServiceConnected(SettingsFragment.java:184)
E/AndroidRuntime( 7863):        at com.nutomic.syncthingandroid.activities.SyncthingActivity.onServiceConnected(SyncthingActivity.java:51)
E/AndroidRuntime( 7863):        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1208)
E/AndroidRuntime( 7863):        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1225)
E/AndroidRuntime( 7863):        at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime( 7863):        at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 7863):        at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 7863):        at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime( 7863):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7863):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 7863):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime( 7863):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
W/ActivityManager( 2026):   Force finishing activity 1 com.nutomic.syncthingandroid/.activities.SettingsActivity
W/ActivityManager( 2026):   Force finishing activity 2 com.nutomic.syncthingandroid/.activities.MainActivity
I/OpenGLRenderer( 2026): Initialized EGL, version 1.4
V/GetTask ( 7863): Calling Rest API at https://127.0.0.1:8384/rest/db/status
```

**Comment by AudriusButkevicius** [comment]
Number of ann servers being weird is a syncthing thing, though 0/0 is a android thing.

**Comment by Nutomic** [comment]
Yeah I fixed the 0/0 in the commit above.
