### ISSUE TITLE
Syncthing-android crashes instantly

### ISSUE THREAD

**Issue by kisolre** [syncthing/syncthing-android#471]
I installed 0.7.0-beta1 on my S5 and at first it worked just fine. But after a while it started crashing every time. It starts, displays "Loading..." for some time and then crashes. By the time it crashes it usually suceeds in sending at least one file (I copy a file to the synched folder and it shows on the PC). This is past of a " adb logcat -d -v time" result after a crash.
```
10-26 19:47:47.617 E/AndroidRuntime(26414): FATAL EXCEPTION: main

10-26 19:47:47.617 E/AndroidRuntime(26414): Process: com.nutomic.syncthingandroid, PID: 26414

10-26 19:47:47.617 E/AndroidRuntime(26414): java.lang.RuntimeException: Invalid usage report value

10-26 19:47:47.617 E/AndroidRuntime(26414): 	at com.nutomic.syncthingandroid.syncthing.RestApi.getUsageReportAccepted(RestApi.java:986)

10-26 19:47:47.617 E/AndroidRuntime(26414): 	at com.nutomic.syncthingandroid.activities.MainActivity.onApiChange(MainActivity.java:75)

10-26 19:47:47.617 E/AndroidRuntime(26414): 	at com.nutomic.syncthingandroid.syncthing.SyncthingService.registerOnApiChangeListener(SyncthingService.java:443)

10-26 19:47:47.617 E/AndroidRuntime(26414): 	at com.nutomic.syncthingandroid.activities.MainActivity.onServiceConnected(MainActivity.java:258)

10-26 19:47:47.617 E/AndroidRuntime(26414): 	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1265)

10-26 19:47:47.617 E/AndroidRuntime(26414): 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1282)

10-26 19:47:47.617 E/AndroidRuntime(26414): 	at android.os.Handler.handleCallback(Handler.java:739)

10-26 19:47:47.617 E/AndroidRuntime(26414): 	at android.os.Handler.dispatchMessage(Handler.java:95)

10-26 19:47:47.617 E/AndroidRuntime(26414): 	at android.os.Looper.loop(Looper.java:145)

10-26 19:47:47.617 E/AndroidRuntime(26414): 	at android.app.ActivityThread.main(ActivityThread.java:5832)

10-26 19:47:47.617 E/AndroidRuntime(26414): 	at java.lang.reflect.Method.invoke(Native Method)

10-26 19:47:47.617 E/AndroidRuntime(26414): 	at java.lang.reflect.Method.invoke(Method.java:372)

10-26 19:47:47.617 E/AndroidRuntime(26414): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)

10-26 19:47:47.617 E/AndroidRuntime(26414): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

10-26 19:47:47.627 V/ApplicationPolicy(  935): isApplicationStateBlocked userId 0 pkgname com.nutomic.syncthingandroid

10-26 19:47:47.627 D/LockPatternUtilsCache( 1188): getCarrierLockPlusMode()

10-26 19:47:47.627 D/LockPatternUtilsCache( 1188): value : false

10-26 19:47:47.627 D/LockPatternUtilsCache( 1188): getCarrierLockPlusMode()

10-26 19:47:47.627 D/LockPatternUtilsCache( 1188): value : false

10-26 19:47:47.627 W/ActivityManager(  935):   Force finishing activity com.nutomic.syncthingandroid/.activities.MainActivity
```

**Comment by Nutomic** [comment]
@AudriusButkevicius You wanted to make a pr for this? ;)

**Comment by kisolre** [comment]
Really weird is that although when trying to start Syncthing it crashes the actual sync continues. PC shows S5 as connected and taking pictures (S5 syncs DCIM folder) sends them to the PC.

**Comment by AudriusButkevicius** [comment]
Its just the ui which crashes.
