### ISSUE TITLE
Menu-key crashes app 

### ISSUE THREAD

**Issue by NeroBurner** [syncthing/syncthing-android#499]
Syncthing-Version: v0.12.2
St-Android-Version: 0.7.4
Device: Samsung Galaxy S3 (i9300)
Android-version: 4.4.4 (Cyanogenmod 11)

When in the Home-Screen (just after starting the app) and hitting the Menu-key the app crashes. The crash-dialog-box with "Unfortunately, Syncthing has stopped." appears.

Expected behaviour: Open the side menu

**Comment by Nutomic** [comment]
Can you post a logcat of the crash please?

**Comment by NeroBurner** [comment]
[Syncthingerror-2015-11-16-18-03-36.txt](https://github.com/syncthing/syncthing-android/files/35760/Syncthingerror-2015-11-16-18-03-36.txt)

**Comment by Smeat** [comment]
I have the same Problem.
Was working with Syncthing v0.12.1 and St-Android 0.7.0. 
With the newest version (0.12.1 and 0.7.4) I get a crash.

    E/MessageQueue-JNI(22592): java.lang.IllegalArgumentException: No drawer view found with gravity RIGHT
    E/MessageQueue-JNI(22592): 	at android.support.v4.widget.DrawerLayout.openDrawer(DrawerLayout.java:1464)
    E/MessageQueue-JNI(22592): 	at com.nutomic.syncthingandroid.activities.MainActivity.onKeyDown(MainActivity.java:356)
    E/MessageQueue-JNI(22592): 	at android.view.KeyEvent.dispatch(KeyEvent.java:2640)
    E/MessageQueue-JNI(22592): 	at android.app.Activity.dispatchKeyEvent(Activity.java:2423)
    ...

Tested on 3 different devices with different Android versions.
