### ISSUE TITLE
Crash opening WiFi whitelist

### ISSUE THREAD

**Issue by scienmind** [syncthing/syncthing-android#620]
After upgrading to Android 6, selecting "Restrict to certain WiFi networks" crashes the app:

1. Open the SyncThing Android application
2. Open application's settings
3. Enable "Background syncing"
4. Enable "WiFi Only" syncing
5. Click "Restrict to certain WiFi networks"
-Application Crushes-

I tried deleting ST's data, and re-importing the config. Still same crush...

ST v.0.12.20
Android wrapper v.0.7.11 (latest f-droid release...)
OS: CM13 latest stable snapshot

Log:
```
--------- beginning of main
04-18 16:39:50.645 21384 21404 I chatty : uid=10139(com.nutomic.syncthingandroid) expire 14 lines
04-18 16:40:06.121 21384 21444 I chatty : uid=10139(com.nutomic.syncthingandroid) expire 11 lines
04-18 16:40:22.095 21384 21384 I chatty : uid=10139(com.nutomic.syncthingandroid) expire 10 lines
04-18 16:43:25.296 21384 21444 I chatty : uid=10139(com.nutomic.syncthingandroid) expire 10 lines
04-18 16:44:22.105 21384 21404 I chatty : uid=10139(com.nutomic.syncthingandroid) expire 6 lines
04-18 16:44:56.138 21384 21409 I chatty : uid=10139(com.nutomic.syncthingandroid) expire 3 lines
04-18 16:45:34.165 21384 21394 I chatty : uid=10139(com.nutomic.syncthingandroid) expire 1 line
04-18 16:45:34.327 21384 21403 I chatty : uid=10139(com.nutomic.syncthingandroid) expire 1 line
04-18 16:46:27.026 22656 22656 I chatty : uid=10139(com.nutomic.syncthingandroid) expire 10 lines
04-18 16:46:27.378 22656 22672 I chatty : uid=10139(com.nutomic.syncthingandroid) expire 2 lines
04-18 16:46:27.531 22656 22673 I chatty : uid=10139(com.nutomic.syncthingandroid) expire 1 line
04-18 16:46:27.548 22676 22676 I chatty : uid=10139(com.nutomic.syncthingandroid) chmod expire 2 lines
04-18 16:46:27.957 22656 22679 I chatty : uid=10139(com.nutomic.syncthingandroid) expire 10 lines
04-18 16:46:28.709 22691 22691 I chatty : uid=10139(com.nutomic.syncthingandroid) ps expire 14 lines
04-18 16:46:28.747 22656 22693 I chatty : uid=10139(com.nutomic.syncthingandroid) expire 3 lines
04-18 16:46:28.898 22656 22690 I chatty : uid=10139(com.nutomic.syncthingandroid) expire 1 line
04-18 16:46:28.899 22656 22681 I chatty : uid=10139(com.nutomic.syncthingandroid) expire 2 lines
04-18 16:46:38.689 22656 22679 I chatty : uid=10139(com.nutomic.syncthingandroid) expire 20 lines
04-18 16:46:46.564 22656 22715 I chatty : uid=10139(com.nutomic.syncthingandroid) expire 9 lines
04-18 16:46:47.938 22656 22672 I chatty : uid=10139(com.nutomic.syncthingandroid) expire 4 lines
04-18 16:46:47.946 22656 22718 I chatty : uid=10139(com.nutomic.syncthingandroid) expire 175 lines
04-18 16:46:48.188 22656 22666 I chatty : uid=10139(com.nutomic.syncthingandroid) expire 1 line
04-18 16:46:48.495 22656 22718 I chatty : uid=10139(com.nutomic.syncthingandroid) expire 138 lines
04-18 16:46:48.646 22656 22672 I chatty : uid=10139(com.nutomic.syncthingandroid) expire 18 lines
04-18 16:46:49.885 22656 22666 I chatty : uid=10139(com.nutomic.syncthingandroid) expire 1 line
04-18 16:46:50.231 22656 22718 I chatty : uid=10139(com.nutomic.syncthingandroid) expire 67 lines
04-18 16:46:50.359 22656 22672 I chatty : uid=10139(com.nutomic.syncthingandroid) expire 15 lines
04-18 16:46:51.313 22656 22718 I chatty : uid=10139(com.nutomic.syncthingandroid) expire 16 lines
04-18 16:46:51.521 22656 22672 I chatty : uid=10139(com.nutomic.syncthingandroid) expire 2 lines
04-18 16:46:51.526 22656 22718 I chatty : uid=10139(com.nutomic.syncthingandroid) expire 2 lines
04-18 16:46:51.533 22656 22672 I chatty : uid=10139(com.nutomic.syncthingandroid) expire 1 line
04-18 16:46:51.537 22656 22718 I chatty : uid=10139(com.nutomic.syncthingandroid) expire 84 lines
04-18 16:46:51.729 22656 22672 I chatty : uid=10139(com.nutomic.syncthingandroid) expire 19 lines
04-18 16:46:53.094 22656 22718 I chatty : uid=10139(com.nutomic.syncthingandroid) expire 2 lines
04-18 16:46:53.098 22656 22672 I chatty : uid=10139(com.nutomic.syncthingandroid) expire 2 lines
04-18 16:46:53.110 22656 22718 I chatty : uid=10139(com.nutomic.syncthingandroid) expire 28 lines
04-18 16:46:53.403 22656 22672 I chatty : uid=10139(com.nutomic.syncthingandroid) expire 34 lines
04-18 16:46:53.996 22656 22679 I chatty : uid=10139(com.nutomic.syncthingandroid) expire 1 line
04-18 16:46:56.507 22656 22656 I chatty : uid=10139(com.nutomic.syncthingandroid) expire 3 lines
04-18 16:46:59.456 22656 22656 E AndroidRuntime: FATAL EXCEPTION: main
04-18 16:46:59.456 22656 22656 E AndroidRuntime: Process: com.nutomic.syncthingandroid, PID: 22656
04-18 16:46:59.456 22656 22656 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.compareToIgnoreCase(java.lang.String)' on a null object reference
04-18 16:46:59.456 22656 22656 E AndroidRuntime: at com.nutomic.syncthingandroid.preferences.WifiSsidPreference$1.compare(WifiSsidPreference.java:118)
04-18 16:46:59.456 22656 22656 E AndroidRuntime: at com.nutomic.syncthingandroid.preferences.WifiSsidPreference$1.compare(WifiSsidPreference.java:115)
04-18 16:46:59.456 22656 22656 E AndroidRuntime: at java.util.TimSort.countRunAndMakeAscending(TimSort.java:320)
04-18 16:46:59.456 22656 22656 E AndroidRuntime: at java.util.TimSort.sort(TimSort.java:185)
04-18 16:46:59.456 22656 22656 E AndroidRuntime: at java.util.TimSort.sort(TimSort.java:169)
04-18 16:46:59.456 22656 22656 E AndroidRuntime: at java.util.Arrays.sort(Arrays.java:2010)
04-18 16:46:59.456 22656 22656 E AndroidRuntime: at com.nutomic.syncthingandroid.preferences.WifiSsidPreference.loadConfiguredNetworksSorted(WifiSsidPreference.java:115)
04-18 16:46:59.456 22656 22656 E AndroidRuntime: at com.nutomic.syncthingandroid.preferences.WifiSsidPreference.showDialog(WifiSsidPreference.java:54)
04-18 16:46:59.456 22656 22656 E AndroidRuntime: at android.preference.DialogPreference.onClick(DialogPreference.java:277)
04-18 16:46:59.456 22656 22656 E AndroidRuntime: at android.preference.Preference.performClick(Preference.java:994)
04-18 16:46:59.456 22656 22656 E AndroidRuntime: at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:214)
04-18 16:46:59.456 22656 22656 E AndroidRuntime: at android.widget.AdapterView.performItemClick(AdapterView.java:310)
04-18 16:46:59.456 22656 22656 E AndroidRuntime: at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
04-18 16:46:59.456 22656 22656 E AndroidRuntime: at android.widget.AbsListView$PerformClick.run(AbsListView.java:3066)
04-18 16:46:59.456 22656 22656 E AndroidRuntime: at android.widget.AbsListView$3.run(AbsListView.java:3903)
04-18 16:46:59.456 22656 22656 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:739)
04-18 16:46:59.456 22656 22656 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:95)
04-18 16:46:59.456 22656 22656 E AndroidRuntime: at android.os.Looper.loop(Looper.java:148)
04-18 16:46:59.456 22656 22656 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:5466)
04-18 16:46:59.456 22656 22656 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
04-18 16:46:59.456 22656 22656 E AndroidRuntime: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
04-18 16:46:59.456 22656 22656 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
04-18 16:46:59.456 22656 22656 E AndroidRuntime: at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
04-18 16:47:01.242 22760 22760 I chatty : uid=10139(com.nutomic.syncthingandroid) expire 9 lines
04-18 16:47:01.566 22760 22778 I chatty : uid=10139(com.nutomic.syncthingandroid) RenderThread expire 3 lines
04-18 16:47:01.693 22760 22779 I chatty : uid=10139(com.nutomic.syncthingandroid) AsyncTask #1 expire 2 lines
04-18 16:47:02.125 22786 22786 I chatty : uid=10139(com.nutomic.syncthingandroid) chmod expire 2 lines
04-18 16:47:02.243 22760 22783 I chatty : uid=10139(com.nutomic.syncthingandroid) AsyncTask #2 expire 1 line
04-18 16:47:02.678 22760 22789 I chatty : uid=10139(com.nutomic.syncthingandroid) Thread-1380 expire 30 lines
04-18 16:47:03.306 22802 22802 I chatty : uid=10139(com.nutomic.syncthingandroid) ps expire 14 lines
04-18 16:47:03.495 22760 22801 I chatty : uid=10139(com.nutomic.syncthingandroid) expire 1 line
04-18 16:47:03.498 22760 22791 I chatty : uid=10139(com.nutomic.syncthingandroid) expire 2 lines
04-18 16:47:09.300 22760 22821 I chatty : uid=10139(com.nutomic.syncthingandroid) AsyncTask #3 expire 9 lines
04-18 16:47:10.682 22760 22824 I chatty : uid=10139(com.nutomic.syncthingandroid) expire 257 lines
04-18 16:47:10.799 22760 22779 I chatty : uid=10139(com.nutomic.syncthingandroid) AsyncTask #1 expire 4 lines
04-18 16:47:11.054 22760 22770 I chatty : uid=10139(com.nutomic.syncthingandroid) HeapTaskDaemon expire 1 line
04-18 16:47:11.412 22760 22824 I chatty : uid=10139(com.nutomic.syncthingandroid) expire 137 lines
04-18 16:47:11.822 22760 22779 I chatty : uid=10139(com.nutomic.syncthingandroid) AsyncTask #1 expire 3 lines
04-18 16:47:11.878 22760 22824 I chatty : uid=10139(com.nutomic.syncthingandroid) expire 12 lines
04-18 16:47:11.913 22760 22824 V FolderObserver: observer created for FOLDER in FOLDER
...
04-18 16:47:12.372 22760 22824 V FolderObserver: observer created for FOLDER in FOLDER
04-18 16:47:12.496 22760 22779 V GetTask : API call result: {"connections":{"IDIDIDID-IDIDIDID-IDIDIDID":{"address":"","at":"0001-01-01T00:00:00Z","clientVersion":"","connected":false,"inBytesTotal":0,"outBytesTotal":0,"paused":false,"type":"direct-accept"},"IDIDIDID-IDIDIDID-IDIDIDID":{"address":"","at":"0001-01-01T00:00:00Z","clientVersion":"","connected":false,"inBytesTotal":0,"outBytesTotal":0,"paused":false,"type":"direct-accept"},"IDIDIDID-IDIDIDID-IDIDIDID":{"address":"","at":"0001-01-01T00:00:00Z","clientVersion":"","connected":false,"inBytesTotal":0,"outBytesTotal":0,"paused":false,"type":"direct-accept"},"IDIDIDID-IDIDIDID-IDIDIDID":{"address":"","at":"0001-01-01T00:00:00Z","clientVersion":"","connected":false,"inBytesTotal":0,"outBytesTotal":0,"paused":false,"type":"direct-accept"},"IDIDIDID-IDIDIDID-IDIDIDID":{"address":"","at":"0001-01-01T00:00:00Z","clientVersion":"","connected":false,"inBytesTotal":0,"outBytesTotal":0,"paused":false,"type":"direct-accept"}},"total":{"address":"","at":"2016-04-18T13:47:12.481723165Z","clientVersion":"","connected":false,"inBytesTotal":0,"outBytesTotal":0,"paused":false,"type":"direct-accept"}}
04-18 16:47:12.496 22760 22779 V GetTask : Calling Rest API at https://IP:PORT/rest/system/connections
04-18 16:47:12.519 22760 22779 W System : ClassLoader referenced unknown path: /system/framework/tcmclient.jar
04-18 16:47:12.791 22760 22779 V GetTask : API call result: {"connections":{"IDIDIDID-IDIDIDID-IDIDIDID":{"address":"","at":"0001-01-01T00:00:00Z","clientVersion":"","connected":false,"inBytesTotal":0,"outBytesTotal":0,"paused":false,"type":"direct-accept"},"IDIDIDID-IDIDIDID-IDIDIDID":{"address":"","at":"0001-01-01T00:00:00Z","clientVersion":"","connected":false,"inBytesTotal":0,"outBytesTotal":0,"paused":false,"type":"direct-accept"},"IDIDIDID-IDIDIDID-IDIDIDID":{"address":"","at":"0001-01-01T00:00:00Z","clientVersion":"","connected":false,"inBytesTotal":0,"outBytesTotal":0,"paused":false,"type":"direct-accept"},"IDIDIDID-IDIDIDID-IDIDIDID":{"address":"","at":"0001-01-01T00:00:00Z","clientVersion":"","connected":false,"inBytesTotal":0,"outBytesTotal":0,"paused":false,"type":"direct-accept"},"IDIDIDID-IDIDIDID-IDIDIDID":{"address":"","at":"0001-01-01T00:00:00Z","clientVersion":"","connected":false,"inBytesTotal":0,"outBytesTotal":0,"paused":false,"type":"direct-accept"}},"total":{"address":"","at":"2016-04-18T13:47:12.783996933Z","clientVersion":"","connected":false,"inBytesTotal":0,"outBytesTotal":0,"paused":false,"type":"direct-accept"}}
04-18 16:47:12.792 22760 22779 V GetTask : Calling Rest API at https://IP:PORT/rest/db/status
04-18 16:47:12.799 22760 22779 W System : ClassLoader referenced unknown path: /system/framework/tcmclient.jar
04-18 16:47:12.983 22760 22779 V GetTask : API call result: {"globalBytes":378161898,"globalDeleted":0,"globalFiles":79,"ignorePatterns":true,"inSyncBytes":378161898,"inSyncFiles":79,"invalid":"","localBytes":378161898,"localDeleted":0,"localFiles":79,"needBytes":0,"needFiles":0,"state":"idle","stateChanged":"2016-04-18T13:47:08.58369173Z","version":2823}
04-18 16:47:12.987 22760 22779 V GetTask : Calling Rest API at https://IP:PORT/rest/db/status
04-18 16:47:13.026 22760 22779 W System : ClassLoader referenced unknown path: /system/framework/tcmclient.jar
...
```

**Comment by capi** [comment]
The cause `return lhs.SSID.compareToIgnoreCase(rhs.SSID);`. This means that your OS returns a saved WiFi which has no SSID. This sounds like a bug (because what is a WiFi without an SSID?). (see [API documentation][1]).

Have you by chance added a WiFi manually? We can add a check for `null` there (I actually had once and removed it during the review process for not making sense in my opinion).

[1]: http://developer.android.com/reference/android/net/wifi/WifiConfiguration.html#SSID

**Comment by capi** [comment]
Since you said you have CM13, did you revoke any permissions / not grant WiFi permissions to Syncthing? Because I really cannot understand how the SSID can be `null`.

**Comment by scienmind** [comment]
Hi, permissions is the first thing I thought about - all fine there.
However, I examined the wpa_supplicant file with the network list, and indeed have found a network with "limited info" there - just security type, and pretty much nothing else... 
I remember attempting to connect to a corporate network, and cancelling after a failed password entry. 

I don't know if saving "partial info" was a correct behavior on android's part or not. Anyway's, after deleting it and rebooting, the crash is gone.

If according to android's docs such entries should never exist (are they?), then it's a ROM bug, and I'll close the issue.

**Comment by capi** [comment]
It was my understanding of the docs, but after looking in some other parts of the Android code, they do some null-checks on the SSID, so I assume there might be cases. My current fix which has been merged by @Nutomic, treates them like an empty SSID. A better approach might be to filter out such networks at all. Let's see if the issue pops up again, then I'll improve on handling.

**Comment by scienmind** [comment]
Defending against nulls there is indeed a good idea :)

**Comment by scienmind** [comment]
And since the fix is merged with the master, I'll close this for now

**Comment by Nutomic** [comment]
Right, this should have been closed automatically. 

@capi I think Github doesn't understand "fix for #issue", only "fixes #issue".
