### ISSUE TITLE
Adding a device causes a crash

### ISSUE THREAD

**Issue by vext01** [syncthing/syncthing-android#632]
I think since the last update, clicking to add a new device causes "unfortunately syncthing has stopped".

Sorry I don't know how to get a trace.

**Comment by vext01** [comment]
FWIW: This is still persisting on the release that was made yesterday.

**Comment by zuk** [comment]
Seeing this in `0.7.16`/`v0.12.22` when adding a new device:

```
04-30 11:50:55.856 23454 23454 D AndroidRuntime: Shutting down VM
04-30 11:50:55.868 23454 23454 E AndroidRuntime: FATAL EXCEPTION: main
04-30 11:50:55.868 23454 23454 E AndroidRuntime: Process: com.nutomic.syncthingandroid, PID: 23454
04-30 11:50:55.868 23454 23454 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nutomic.syncthingandroid/com.nutomic.syncthingandroid.activities.SettingsActivity}: android.view.InflateException: Binary XML file line #49: Binary XML file line #49: Error inflating class EditText
04-30 11:50:55.868 23454 23454 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
04-30 11:50:55.868 23454 23454 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
04-30 11:50:55.868 23454 23454 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
04-30 11:50:55.868 23454 23454 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
04-30 11:50:55.868 23454 23454 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-30 11:50:55.868 23454 23454 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
04-30 11:50:55.868 23454 23454 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5422)
04-30 11:50:55.868 23454 23454 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-30 11:50:55.868 23454 23454 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
04-30 11:50:55.868 23454 23454 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
04-30 11:50:55.868 23454 23454 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #49: Binary XML file line #49: Error inflating class EditText
04-30 11:50:55.868 23454 23454 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
04-30 11:50:55.868 23454 23454 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
04-30 11:50:55.868 23454 23454 E AndroidRuntime: 	at com.nutomic.syncthingandroid.fragments.DeviceFragment.onCreateView(DeviceFragment.java:203)
04-30 11:50:55.868 23454 23454 E AndroidRuntime: 	at android.app.Fragment.performCreateView(Fragment.java:2220)
04-30 11:50:55.868 23454 23454 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:973)
04-30 11:50:55.868 23454 23454 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
04-30 11:50:55.868 23454 23454 E AndroidRuntime: 	at android.app.BackStackRecord.run(BackStackRecord.java:793)
04-30 11:50:55.868 23454 23454 E AndroidRuntime: 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535)
04-30 11:50:55.868 23454 23454 E AndroidRuntime: 	at android.app.FragmentController.execPendingActions(FragmentController.java:325)
04-30 11:50:55.868 23454 23454 E AndroidRuntime: 	at android.app.Activity.performStart(Activity.java:6267)
04-30 11:50:55.868 23454 23454 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
04-30 11:50:55.868 23454 23454 E AndroidRuntime: 	... 9 more
04-30 11:50:55.868 23454 23454 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #49: Error inflating class EditText
04-30 11:50:55.868 23454 23454 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:782)
04-30 11:50:55.868 23454 23454 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
04-30 11:50:55.868 23454 23454 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
04-30 11:50:55.868 23454 23454 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
04-30 11:50:55.868 23454 23454 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
04-30 11:50:55.868 23454 23454 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
04-30 11:50:55.868 23454 23454 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
04-30 11:50:55.868 23454 23454 E AndroidRuntime: 	... 19 more
04-30 11:50:55.868 23454 23454 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_tag_text_outline_black_24dp.xml from drawable resource ID #0x7f020075
04-30 11:50:55.868 23454 23454 E AndroidRuntime: 	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2603)
04-30 11:50:55.868 23454 23454 E AndroidRuntime: 	at android.content.res.Resources.loadDrawable(Resources.java:2503)
04-30 11:50:55.868 23454 23454 E AndroidRuntime: 	at android.content.res.TypedArray.getDrawable(TypedArray.java:870)
04-30 11:50:55.868 23454 23454 E AndroidRuntime: 	at android.widget.TextView.<init>(TextView.java:881)
04-30 11:50:55.868 23454 23454 E AndroidRuntime: 	at android.widget.EditText.<init>(EditText.java:64)
04-30 11:50:55.868 23454 23454 E AndroidRuntime: 	at android.widget.EditText.<init>(EditText.java:60)
04-30 11:50:55.868 23454 23454 E AndroidRuntime: 	at android.support.v7.widget.AppCompatEditText.<init>(AppCompatEditText.java:60)
04-30 11:50:55.868 23454 23454 E AndroidRuntime: 	at android.support.v7.widget.AppCompatEditText.<init>(AppCompatEditText.java:56)
04-30 11:50:55.868 23454 23454 E AndroidRuntime: 	at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:108)
04-30 11:50:55.868 23454 23454 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:972)
04-30 11:50:55.868 23454 23454 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:1030)
04-30 11:50:55.868 23454 23454 E AndroidRuntime: 	at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
04-30 11:50:55.868 23454 23454 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:746)
04-30 11:50:55.868 23454 23454 E AndroidRuntime: 	... 25 more
04-30 11:50:55.868 23454 23454 E AndroidRuntime: Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #4: <item> tag requires a 'drawable' attribute or child tag defining a drawable
04-30 11:50:55.868 23454 23454 E AndroidRuntime: 	at android.graphics.drawable.StateListDrawable.inflateChildElements(StateListDrawable.java:182)
04-30 11:50:55.868 23454 23454 E AndroidRuntime: 	at android.graphics.drawable.StateListDrawable.inflate(StateListDrawable.java:115)
04-30 11:50:55.868 23454 23454 E AndroidRuntime: 	at android
04-30 11:50:55.871  5096 22207 W ActivityManager:   Force finishing activity com.nutomic.syncthingandroid/.activities.SettingsActivity
04-30 11:50:55.873  5096 22207 W ActivityManager:   Force finishing activity com.nutomic.syncthingandroid/.activities.MainActivity
```

**Comment by kowach** [comment]
I can confirm this error on two Androids 6.0.

**Comment by oscarmlage** [comment]
I can confirm it too, in a Nexus 6p brand new with Android 6.0 too

**Comment by vext01** [comment]
Glad it's not just me.

For now you can  work around the crash by using the web interface to add the device, but I hope a proper fix comes soon.

**Comment by oscarmlage** [comment]
@vext01 Thank you for the tip. Trying right now. One not-related question, is the "background" mode (only wifi) working for any of you?

**Comment by vext01** [comment]
It was broken in the previous release. Check you are up to date. Otherwise a regression?

**Comment by Nutomic** [comment]
Fuck, every time I update a dependency, something breaks. Get your shit together Google...

**Comment by arkhan** [comment]
Hello, I have the same issue with 0.7.21 version, in Android 6.0.1, in version 0.7.20 does not happen

**Comment by Nutomic** [comment]
@arkhan Please open a new issue with logcat.

**Comment by eastein** [comment]
I'm still seeing this on v0.13.7 on my Android device. Android 6.0.
