### ISSUE TITLE
Tapping a device in the devices tab causes a crash

### ISSUE THREAD

**Issue by vext01** [syncthing/syncthing-android#693]
Version 0.7.2.1 on an LG-G4.

"Unfortunatley, syncthing has stopped"

**Comment by licaon-kter** [comment]
F-Droid or Google Play store?
Android version?

Do also save logs (Settings ->Log and Android log).

**Comment by vext01** [comment]
It's from the play store I think.

Android-6.0, but vendor customised (LG).

I think this is the relevant data:

```
--------- beginning of crash
07-08 17:32:34.517  6352  6352 E AndroidRuntime: FATAL EXCEPTION: main
07-08 17:32:34.517  6352  6352 E AndroidRuntime: Process: com.nutomic.syncthingandroid, PID: 6352
07-08 17:32:34.517  6352  6352 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nutomic.syncthingandroid/com.nutomic.syncthingandroid.activities.SettingsActivity}: android.view.InflateException: Binary XML file line #49: Binary XML file line #49: Error inflating class EditText
07-08 17:32:34.517  6352  6352 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2434)
07-08 17:32:34.517  6352  6352 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)
07-08 17:32:34.517  6352  6352 E AndroidRuntime: 	at android.app.ActivityThread.access$900(ActivityThread.java:157)
07-08 17:32:34.517  6352  6352 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356)
07-08 17:32:34.517  6352  6352 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-08 17:32:34.517  6352  6352 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
07-08 17:32:34.517  6352  6352 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5525)
07-08 17:32:34.517  6352  6352 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-08 17:32:34.517  6352  6352 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
07-08 17:32:34.517  6352  6352 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
07-08 17:32:34.517  6352  6352 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #49: Binary XML file line #49: Error inflating class EditText
07-08 17:32:34.517  6352  6352 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
07-08 17:32:34.517  6352  6352 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
07-08 17:32:34.517  6352  6352 E AndroidRuntime: 	at com.nutomic.syncthingandroid.fragments.DeviceFragment.onCreateView(DeviceFragment.java:203)
07-08 17:32:34.517  6352  6352 E AndroidRuntime: 	at android.app.Fragment.performCreateView(Fragment.java:2229)
07-08 17:32:34.517  6352  6352 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:973)
07-08 17:32:34.517  6352  6352 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
07-08 17:32:34.517  6352  6352 E AndroidRuntime: 	at android.app.BackStackRecord.run(BackStackRecord.java:793)
07-08 17:32:34.517  6352  6352 E AndroidRuntime: 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535)
07-08 17:32:34.517  6352  6352 E AndroidRuntime: 	at android.app.FragmentController.execPendingActions(FragmentController.java:325)
07-08 17:32:34.517  6352  6352 E AndroidRuntime: 	at android.app.Activity.performStart(Activity.java:6287)
07-08 17:32:34.517  6352  6352 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2397)
07-08 17:32:34.517  6352  6352 E AndroidRuntime: 	... 9 more
07-08 17:32:34.517  6352  6352 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #49: Error inflating class EditText
07-08 17:32:34.517  6352  6352 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:782)
07-08 17:32:34.517  6352  6352 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
07-08 17:32:34.517  6352  6352 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
07-08 17:32:34.517  6352  6352 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
07-08 17:32:34.517  6352  6352 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
07-08 17:32:34.517  6352  6352 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
07-08 17:32:34.517  6352  6352 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
07-08 17:32:34.517  6352  6352 E AndroidRuntime: 	... 19 more
07-08 17:32:34.517  6352  6352 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_tag_text_outline_black_24dp.xml from drawable resource ID #0x7f020077
07-08 17:32:34.517  6352  6352 E AndroidRuntime: 	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2748)
07-08 17:32:34.517  6352  6352 E AndroidRuntime: 	at android.content.res.Resources.loadDrawable(Resources.java:2643)
07-08 17:32:34.517  6352  6352 E AndroidRuntime: 	at android.content.res.TypedArray.getDrawable(TypedArray.java:870)
07-08 17:32:34.517  6352  6352 E AndroidRuntime: 	at android.widget.TextView.<init>(TextView.java:913)
07-08 17:32:34.517  6352  6352 E AndroidRuntime: 	at android.widget.EditText.<init>(EditText.java:64)
07-08 17:32:34.517  6352  6352 E AndroidRuntime: 	at android.widget.EditText.<init>(EditText.java:60)
07-08 17:32:34.517  6352  6352 E AndroidRuntime: 	at android.support.v7.widget.AppCompatEditText.<init>(AppCompatEditText.java:60)
07-08 17:32:34.517  6352  6352 E AndroidRuntime: 	at android.support.v7.widget.AppCompatEditText.<init>(AppCompatEditText.java:56)
07-08 17:32:34.517  6352  6352 E AndroidRuntime: 	at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:112)
07-08 17:32:34.517  6352  6352 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:1008)
07-08 17:32:34.517  6352  6352 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:1067)
07-08 17:32:34.517  6352  6352 E AndroidRuntime: 	at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
07-08 17:32:34.517  6352  6352 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:746)
07-08 17:32:34.517  6352  6352 E AndroidRuntime: 	... 25 more
07-08 17:32:34.517  6352  6352 E AndroidRuntime: Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #4: <item> tag requires a 'drawable' attribute or child tag defining a drawable
07-08 17:32:34.517  6352  6352 E AndroidRuntime: 	at android.graphics.drawable.StateListDrawable.inflateChildElements(StateListDrawable.java:182)
07-08 17:32:34.517  6352  6352 E AndroidRuntime: 	at android.graphics.drawable.StateListDrawable.inflate(StateListDrawable.java:115)
07-08 17:32:34.517  6352  6352 E AndroidRuntime: 	at 
07-08 17:32:42.542 15691 15691 I Timeline: Timeline: Activity_idle id: android.os.BinderProxy@b2a499 time:409738137
```

**Comment by opie4624** [comment]
I have the same issue on a Motorola Turbo 2 (Android 6.0) running Syncthing Android v0.7.21 from the Play store. This happens when tapping a device, tapping a "add this device" notification, or tapping the + button to add a new device.

**Comment by Nutomic** [comment]
Same issue as #690.

**Comment by fr34kyn01535** [comment]
Well, can't spot whats wrong in here: https://github.com/syncthing/syncthing-android/blob/a04a05b8e8a552004601fc0bd66722c71ac9f81c/src/main/res/layout/fragment_device.xml#L54
