### ISSUE TITLE
Syncthing binary panic-ed but frontend is still spinning loading

### ISSUE THREAD

**Issue by Holi0317** [syncthing/syncthing-android#759]
The database lock of Syncthing will be corrupted sometimes for unknown reason. This cause the syncthing-android to show loading spinner forever as syncthing is in panic and will not be able to start.

I have to remove the whole database files from `/data/user/0/com.nutomic.syncthingandroid/files/index-v0.14.0.db` in order to boot syncthing.

syncthing-android should stop spinning loading if the binary has panic-ed and show logs from the binary. Therefore user can troubleshoot without using logcat.
## Logcat output

```
panic: leveldb/table: corruption on data-block (pos=224193): checksum mismatch, want=0xe9fb4f5f got=0xaea13a [file=000041.ldb]
goroutine 1 [running]:
panic(0x612f70, 0x11dbf460)
  /home/felix/workspace/syncthing-android/ext/golang/dist/go-linux-arm/src/runtime/panic.go:481 +0x330
github.com/syncthing/syncthing/lib/db.(*Instance).checkGlobals(0x1112c360, 0x10dfd538, 0x5, 0x8, 0x10d534d0)
  /home/felix/workspace/syncthing-android/ext/syncthing/src/github.com/syncthing/syncthing/lib/db/leveldb_dbinstance.go:600 +0x504
github.com/syncthing/syncthing/lib/db.NewFileSet(0x11065bb0, 0x5, 0x1112c360, 0x10e2b270)
  /home/felix/workspace/syncthing-android/ext/syncthing/src/github.com/syncthing/syncthing/lib/db/set.go:109 +0x268
github.com/syncthing/syncthing/lib/model.(*Model).addFolderLocked(0x10d64160, 0x11065bb0, 0x5, 0x0, 0x0, 0x1113a760, 0x1a, 0x0, 0x1105b800, 0x4, ...)
  /home/felix/workspace/syncthing-android/ext/syncthing/src/github.com/syncthing/syncthing/lib/model/model.go:304 +0x74
github.com/syncthing/syncthing/lib/model.(*Model).AddFolder(0x10d64160, 0x11065bb0, 0x5, 0x0, 0x0, 0x1113a760, 0x1a, 0x0, 0x1105b800, 0x4, ...)
  /home/felix/workspace/syncthing-android/ext/syncthing/src/github.com/syncthing/syncthing/lib/model/model.go:298 +0xb4
main.syncthingMain(0xff896b28, 0x2f, 0x0, 0x0, 0x0, 0x0, 0x1, 0x6a6e84, 0x1, 0x0, ...)
  /home/felix/workspace/syncthing-android/ext/syncthing/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:705 +0x1928
main.main()
  /home/felix/workspace/syncthing-android/ext/syncthing/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:373 +0x75c
goroutine 33 [select]:
github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0x10d82600)
  /home/felix/workspace/syncthing-android/ext/syncthing/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:90 +0x454
created by github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.openDB
  /home/felix/workspace/syncthing-android/ext/syncthing/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db.go:141 +0x620
goroutine 7 [syscall]:
os/signal.signal_recv(0x0)
  /home/felix/workspace/syncthing-android/ext/golang/dist/go-linux-arm/src/runtime/sigqueue.go:116 +0x190
os/signal.loop()
  /home/felix/workspace/syncthing-android/ext/golang/dist/go-linux-arm/src/os/signal/signal_unix.go:22 +0x14
created by os/signal.init.1
  /home/felix/workspace/syncthing-android/ext/golang/dist/go-linux-arm/src/os/signal/signal_unix.go:28 +0x30
goroutine 8 [chan receive]:
main.trackCPUUsage()
  /home/felix/workspace/syncthing-android/ext/syncthing/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:24 +0x108
created by main.init.3
  /home/felix/workspace/syncthing-android/ext/syncthing/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:17 +0x24
goroutine 9 [select, locked to thread]:
runtime.gopark(0x7c72cc, 0x10d21f8c, 0x6acd60, 0x6, 0xb5cc18, 0x2)
  /home/felix/workspace/syncthing-android/ext/golang/dist/go-linux-arm/src/runtime/proc.go:262 +0x148
runtime.selectgoImpl(0x10d21f8c, 0x0, 0xc)
  /home/felix/workspace/syncthing-android/ext/golang/dist/go-linux-arm/src/runtime/select.go:392 +0x1204
runtime.selectgo(0x10d21f8c)
  /home/felix/workspace/syncthing-android/ext/golang/dist/go-linux-arm/src/runtime/select.go:215 +0x10
runtime.ensureSigM.func1()
  /home/felix/workspace/syncthing-android/ext/golang/dist/go-linux-arm/src/runtime/signal1_unix.go:279 +0x428
runtime.goexit()
  /home/felix/workspace/syncthing-android/ext/golang/dist/go-linux-arm/src/runtime/asm_arm.s:990 +0x4
goroutine 10 [chan receive]:
main.setupSignalHandling.func1(0x10d13c80)
  /home/felix/workspace/syncthing-android/ext/syncthing/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:841 +0x2c
created by main.setupSignalHandling
  /home/felix/workspace/syncthing-android/ext/syncthing/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:843 +0x10c
goroutine 11 [chan receive]:
main.setupSignalHandling.func2(0x10d13dc0)
  /home/felix/workspace/syncthing-android/ext/syncthing/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:851 +0x2c
created by main.setupSignalHandling
  /home/felix/workspace/syncthing-android/ext/syncthing/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:853 +0x240
goroutine 12 [select]:
github.com/syncthing/syncthing/vendor/github.com/thejerf/suture.(*Supervisor).Serve(0x10d59830)
  /home/felix/workspace/syncthing-android/ext/syncthing/src/github.com/syncthing/syncthing/vendor/github.com/thejerf/suture/supervisor.go:338 +0xec8
created by github.com/syncthing/syncthing/vendor/github.com/thejerf/suture.(*Supervisor).ServeBackground
  /home/felix/workspace/syncthing-android/ext/syncthing/src/github.com/syncthing/syncthing/vendor/github.com/thejerf/suture/supervisor.go:297 +0x2c
goroutine 13 [select]:
github.com/syncthing/syncthing/lib/events.(*Subscription).Poll(0x10dfc1c0, 0xf8475800, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  /home/felix/workspace/syncthing-android/ext/syncthing/src/github.com/syncthing/syncthing/lib/events/events.go:239 +0x328
github.com/syncthing/syncthing/lib/events.(*bufferedSubscription).pollingLoop(0x10d168a0)
  /home/felix/workspace/syncthing-android/ext/syncthing/src/github.com/syncthing/syncthing/lib/events/events.go:293 +0x38
created by github.com/syncthing/syncthing/lib/events.NewBufferedSubscription
  /home/felix/workspace/syncthing-android/ext/syncthing/src/github.com/syncthing/syncthing/lib/events/events.go:287 +0x270
goroutine 14 [select]:
github.com/syncthing/syncthing/lib/events.(*Subscription).Poll(0x10dfc200, 0xf8475800, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  /home/felix/workspace/syncthing-android/ext/syncthing/src/github.com/syncthing/syncthing/lib/events/events.go:239 +0x328
github.com/syncthing/syncthing/lib/events.(*bufferedSubscription).pollingLoop(0x10d16900)
  /home/felix/workspace/syncthing-android/ext/syncthing/src/github.com/syncthing/syncthing/lib/events/events.go:293 +0x38
created by github.com/syncthing/syncthing/lib/events.NewBufferedSubscription
  /home/felix/workspace/syncthing-android/ext/syncthing/src/github.com/syncthing/syncthing/lib/events/events.go:287 +0x270
goroutine 15 [select]:
github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0x1105d600)
  /home/felix/workspace/syncthing-android/ext/syncthing/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:206+0x260
created by github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
  /home/felix/workspace/syncthing-android/ext/syncthing/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:237+0x258
goroutine 34 [select]:
github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0x10d82600)
  /home/felix/workspace/syncthing-android/ext/syncthing/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db_state.go:96 +0x1e4
created by github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.openDB
  /home/felix/workspace/syncthing-android/ext/syncthing/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db.go:142 +0x63c
goroutine 35 [select]:
github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0x10d82600)
  /home/felix/workspace/syncthing-android/ext/syncthing/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:804 +0x630
created by github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.openDB
  /home/felix/workspace/syncthing-android/ext/syncthing/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db.go:148 +0x7d8
goroutine 36 [select]:
github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0x10d82600)
  /home/felix/workspace/syncthing-android/ext/syncthing/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:751 +0x20c
created by github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.openDB
  /home/felix/workspace/syncthing-android/ext/syncthing/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db.go:149 +0x7f4
goroutine 37 [select]:
github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).jWriter(0x10d82600)
  /home/felix/workspace/syncthing-android/ext/syncthing/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db_write.go:37 +0x168
created by github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.openDB
  /home/felix/workspace/syncthing-android/ext/syncthing/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db.go:150 +0x810
goroutine 38 [select]:
github.com/syncthing/syncthing/lib/model.(*ProgressEmitter).Serve(0x110610b0)
  /home/felix/workspace/syncthing-android/ext/syncthing/src/github.com/syncthing/syncthing/lib/model/progressemitter.go:57 +0x6fc
created by github.com/syncthing/syncthing/lib/model.NewModel
  /home/felix/workspace/syncthing-android/ext/syncthing/src/github.com/syncthing/syncthing/lib/model/model.go:164 +0xbb0
```
### Version Information

```
App Version: 0.8.6
Syncthing Version: v0.14.8
Device: Nexus 9
Android Version: Android 6.0.1, Cyanogenmod 13.0
```

**Comment by Nutomic** [comment]
I just tried to reproduce it, by running `echo 4321 > 000066.ldb` before starting Syncthing. Turns out Syncthing prints those errors, but gives a return code 2. According to [the docs](https://docs.syncthing.net/users/syncthing.html#exit-codes), that means "Upgrade not available". Sounds like a bug in Syncthing to me.

@calmh @AudriusButkevicius

**Comment by AudriusButkevicius** [comment]
Exit code 2 is also the exit code returned by the runtime on panic.

**Comment by Nutomic** [comment]
Then the documentation is quite misleading.
